"""Combined + Z3-optimized constraints for _ZN2at6native33structured_isin_Scalar_Tensor_out4implERKN3c106ScalarERKNS_6TensorEbbS8_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native33structured_isin_Scalar_Tensor_out4implERKN3c106ScalarERKNS_6TensorEbbS8_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('element', 'Scalar'), ('test_elements', 'Tensor'), ('assume_unique', 'bool'), ('invert', 'bool'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('tensor_10.dtype') == Int('element.dtype')), (IntVal(11) == Int('out.dtype')), (IntVal(1) == Int('out.ndim')), (IntVal(0) == Select(Array('out.sizes', IntSort(), IntSort()), IntVal(0))), Not(And((IntVal(0) == Int('test_elements.device_type')), Not((IntVal(8) == Int('tensor_10.dtype'))), Not((IntVal(5) == Int('tensor_10.dtype'))), Not((IntVal(11) == Int('tensor_10.dtype'))), Not((IntVal(15) == Int('tensor_10.dtype'))), Not((IntVal(0) == Int('tensor_10.dtype'))), Not((IntVal(1) == Int('tensor_10.dtype'))), Not((IntVal(3) == Int('tensor_10.dtype'))), Not((IntVal(4) == Int('tensor_10.dtype'))), Not((IntVal(2) == Int('tensor_10.dtype'))), Not((IntVal(7) == Int('tensor_10.dtype'))), Not((IntVal(6) == Int('tensor_10.dtype'))), Not((IntVal(10) == Int('tensor_10.dtype'))), Not((IntVal(9) == Int('tensor_10.dtype'))), Not((IntVal(23) == Int('tensor_10.dtype'))), Not((IntVal(25) == Int('tensor_10.dtype'))), Not((IntVal(24) == Int('tensor_10.dtype'))), Not((IntVal(26) == Int('tensor_10.dtype'))), Not((IntVal(44) == Int('tensor_10.dtype'))), Not((IntVal(27) == Int('tensor_10.dtype'))), Not((IntVal(28) == Int('tensor_10.dtype'))), Not((IntVal(29) == Int('tensor_10.dtype'))))), (IntVal(12) <= Int('element.dtype')), (IntVal(12) <= Int('test_elements.dtype')))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    element = ScalarVar('element')
    test_elements = TensorVar('test_elements')
    out = TensorVar('out')
    tensor_10 = TensorVar('tensor_10')
    return {'element': element, 'test_elements': test_elements, 'out': out, 'tensor_10': tensor_10}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
