"""Combined + Z3-optimized constraints for _ZN2at6native8full_outEN3c108ArrayRefIlEERKNS1_6ScalarERNS_6TensorE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native8full_outEN3c108ArrayRefIlEERKNS1_6ScalarERNS_6TensorE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('size', 'int[]'), ('fill_value', 'Scalar'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('size.length') >= IntVal(0)), (Int('size.length') <= IntVal(6)), Or(And(Or((Int('size.length') <= IntVal(0)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(0)) >= IntVal(0))), Or((Int('size.length') <= IntVal(1)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(1)) >= IntVal(0))), Or((Int('size.length') <= IntVal(2)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(2)) >= IntVal(0))), Or((Int('size.length') <= IntVal(3)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(3)) >= IntVal(0))), Or((Int('size.length') <= IntVal(4)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(4)) >= IntVal(0))), Or((Int('size.length') <= IntVal(5)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(5)) >= IntVal(0)))), And(Not((Int('size.length') <= IntVal(0))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(0)) == IntVal(0))), And(Not((Int('size.length') <= IntVal(1))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(1)) == IntVal(0))), And(Not((Int('size.length') <= IntVal(2))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(2)) == IntVal(0))), And(Not((Int('size.length') <= IntVal(3))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(3)) == IntVal(0))), And(Not((Int('size.length') <= IntVal(4))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(4)) == IntVal(0))), And(Not((Int('size.length') <= IntVal(5))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(5)) == IntVal(0)))), (Int('out.ndim') >= IntVal(0)), Not(And(Or(Bool('fill_value.is_inf'), Bool('fill_value.is_nan')), Or((Int('out.dtype') == IntVal(0)), (Int('out.dtype') == IntVal(1)), (Int('out.dtype') == IntVal(2)), (Int('out.dtype') == IntVal(3)), (Int('out.dtype') == IntVal(4)), (Int('out.dtype') == IntVal(27)), (Int('out.dtype') == IntVal(28)), (Int('out.dtype') == IntVal(29))))))),
    ]


def get_axioms() -> list:
    # VALUE fix (added unnegated as a precondition):
    # (1) A negative fill_value cannot be converted to an UNSIGNED out dtype
    #     (uint8=0, uint16=27, uint32=28, uint64=29) or to the unsigned-only
    #     Float8_e8m0fnu=44 → "value cannot be converted to type uintN_t /
    #     Float8_e8m0fnu without overflow". Require fill_value >= 0 there.
    # (2) inf cannot be represented by the finite-only Float8 formats
    #     e4m3fn=24, e5m2fnuz=25, e4m3fnuz=26, e8m0fnu=44 (only e5m2=23 has inf).
    #     Forbid inf for those. (nan/inf into the plain integral dtypes is already
    #     excluded in get_constraints.)
    _out_unsigned = Or(Int('out.dtype') == IntVal(0), Int('out.dtype') == IntVal(27),
                       Int('out.dtype') == IntVal(28), Int('out.dtype') == IntVal(29),
                       Int('out.dtype') == IntVal(44))
    _out_f8_noinf = Or(Int('out.dtype') == IntVal(24), Int('out.dtype') == IntVal(25),
                       Int('out.dtype') == IntVal(26), Int('out.dtype') == IntVal(44))
    return [
        Implies(_out_unsigned, Real('fill_value.real_val') >= RealVal(0)),
        Implies(_out_f8_noinf, Not(Bool('fill_value.is_inf'))),
    ]


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
