"""Combined + Z3-optimized constraints for _ZN2at6native4div_ERNS_6TensorERKN3c106ScalarESt8optionalISt17basic_string_viewIcSt11char_traitsIcEEE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native4div_ERNS_6TensorERKN3c106ScalarESt8optionalISt17basic_string_viewIcSt11char_traitsIcEEE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('other', 'Scalar'), ('rounding_mode', 'str?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('self.ndim') >= IntVal(0)), If(Bool('rounding_mode.present'), Or(And(Or((Int('self.dtype') == IntVal(0)), (Int('self.dtype') == IntVal(1)), (Int('self.dtype') == IntVal(2)), (Int('self.dtype') == IntVal(3)), (Int('self.dtype') == IntVal(4))), Not(Or((Int('other.dtype') == IntVal(8)), (Int('other.dtype') == IntVal(9)), (Int('other.dtype') == IntVal(10)))), Not(Or((Int('other.dtype') == IntVal(5)), (Int('other.dtype') == IntVal(6)), (Int('other.dtype') == IntVal(7)), (Int('other.dtype') == IntVal(15)), (Int('other.dtype') == IntVal(23)), (Int('other.dtype') == IntVal(24)), (Int('other.dtype') == IntVal(25)), (Int('other.dtype') == IntVal(26)), (Int('other.dtype') == IntVal(44))))), And(Or((Int('self.dtype') == IntVal(5)), (Int('self.dtype') == IntVal(6)), (Int('self.dtype') == IntVal(7)), (Int('self.dtype') == IntVal(15))), Not(Or((Int('other.dtype') == IntVal(8)), (Int('other.dtype') == IntVal(9)), (Int('other.dtype') == IntVal(10)))))), Or((Int('self.dtype') == IntVal(9)), (Int('self.dtype') == IntVal(10)), And(Or((Int('self.dtype') == IntVal(5)), (Int('self.dtype') == IntVal(6)), (Int('self.dtype') == IntVal(7)), (Int('self.dtype') == IntVal(15))), Not(Or((Int('other.dtype') == IntVal(8)), (Int('other.dtype') == IntVal(9)), (Int('other.dtype') == IntVal(10))))))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
