"""Combined + Z3-optimized constraints for _ZN2at6native8randpermElSt8optionalINS_9GeneratorEES1_IN3c1010ScalarTypeEES1_INS4_6LayoutEES1_INS4_6DeviceEES1_IbE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native8randpermElSt8optionalINS_9GeneratorEES1_IN3c1010ScalarTypeEES1_INS4_6LayoutEES1_INS4_6DeviceEES1_IbE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('n', 'int'), ('generator', 'Generator?'), ('dtype', 'int?'), ('layout', 'int?'), ('device', 'int?'), ('pin_memory', 'bool?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('n') >= IntVal(0)), Or(Not(Bool('dtype.present')), (Int('dtype.val') == IntVal(0)), (Int('dtype.val') == IntVal(1)), (Int('dtype.val') == IntVal(2)), (Int('dtype.val') == IntVal(3)), (Int('dtype.val') == IntVal(4)), (Int('dtype.val') == IntVal(5)), (Int('dtype.val') == IntVal(6)), (Int('dtype.val') == IntVal(7)), (Int('dtype.val') == IntVal(15))))),
    ]


def get_axioms() -> list:
    # Bound the optional dtype value to REAL torch ScalarType codes (codes outside
    # this set are squashed to None by the concretizer, producing spurious
    # dtype=None over-constraint witnesses). Sound: does not widen the valid set.
    dval = Int('dtype.val')
    _real = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 23, 24, 25, 26, 27, 28, 29, 44)
    return [Or(Not(Bool('dtype.present')), Or(*[dval == c for c in _real]))]


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
