"""Combined + Z3-optimized constraints for _ZN2at6native24structured_ge_Scalar_out4implERKNS_6TensorERKN3c106ScalarES4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from mobile.generator.constraints.model import same_shape, out_is_broadcast  # _OUT_OK_INJECTED

ENTRY = '_ZN2at6native24structured_ge_Scalar_out4implERKNS_6TensorERKN3c106ScalarES4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('other', 'Scalar'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS



def _out_ok():
    _OUT = TensorVar('out')
    return Or(_OUT.numel() == 0, same_shape(_OUT, TensorVar('self')))

def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(_out_ok(), Not((Int('self.dtype') == IntVal(8))), Not((Int('self.dtype') == IntVal(9))), Not((Int('self.dtype') == IntVal(10))), Not((Int('self.dtype') == IntVal(23))), Not((Int('self.dtype') == IntVal(24))), Not((Int('self.dtype') == IntVal(25))), Not((Int('self.dtype') == IntVal(26))), Not((Int('self.dtype') == IntVal(44))), Not((Int('self.dtype') == IntVal(27))), Not((Int('self.dtype') == IntVal(28))), Not((Int('self.dtype') == IntVal(29))), Not((Int('other.dtype') == IntVal(8))), Not((Int('other.dtype') == IntVal(9))), Not((Int('other.dtype') == IntVal(10))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
