"""Combined + Z3-optimized constraints for _ZN2at6native23unsafe_split_with_sizesERKNS_6TensorEN3c108ArrayRefIlEEl.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native23unsafe_split_with_sizesERKNS_6TensorEN3c108ArrayRefIlEEl (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('split_sizes', 'int[]'), ('dim', 'int')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('dim') >= (IntVal(-1) * Int('self.ndim'))), Not((Int('self.ndim') <= Int('dim'))), Or((Int('split_sizes.length') <= IntVal(0)), (Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(0)) >= IntVal(0))), Or((Int('split_sizes.length') <= IntVal(1)), (Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(1)) >= IntVal(0))), Or((Int('split_sizes.length') <= IntVal(2)), (Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(2)) >= IntVal(0))), Or((Int('split_sizes.length') <= IntVal(3)), (Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(3)) >= IntVal(0))), Or((Int('split_sizes.length') <= IntVal(4)), (Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(4)) >= IntVal(0))), Or((Int('split_sizes.length') <= IntVal(5)), (Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(5)) >= IntVal(0))), ((If((Int('split_sizes.length') <= IntVal(0)), IntVal(0), Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(0))) + If((Int('split_sizes.length') <= IntVal(1)), IntVal(0), Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(1))) + If((Int('split_sizes.length') <= IntVal(2)), IntVal(0), Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(2))) + If((Int('split_sizes.length') <= IntVal(3)), IntVal(0), Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(3))) + If((Int('split_sizes.length') <= IntVal(4)), IntVal(0), Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(4))) + If((Int('split_sizes.length') <= IntVal(5)), IntVal(0), Select(Array('split_sizes.data', IntSort(), IntSort()), IntVal(5)))) == Select(Array('self.sizes', IntSort(), IntSort()), If((If((Int('dim') >= IntVal(0)), Int('dim'), (Int('dim') + Int('self.ndim'))) >= IntVal(0)), If((Int('dim') >= IntVal(0)), Int('dim'), (Int('dim') + Int('self.ndim'))), (Int('self.ndim') + If((Int('dim') >= IntVal(0)), Int('dim'), (Int('dim') + Int('self.ndim'))))))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
