"""Combined + Z3-optimized constraints for _ZN2at6native12logspace_outERKN3c106ScalarERKNS_6TensorEldRS5_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native12logspace_outERKN3c106ScalarERKNS_6TensorEldRS5_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('start', 'Scalar'), ('end', 'Tensor'), ('steps', 'int'), ('base', 'float'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Not((IntVal(11) == Int('out.dtype'))), Not((IntVal(8) == Int('out.dtype'))), Not((IntVal(23) == Int('out.dtype'))), Not((IntVal(24) == Int('out.dtype'))), Not((IntVal(25) == Int('out.dtype'))), Not((IntVal(26) == Int('out.dtype'))), Not((IntVal(44) == Int('out.dtype'))), Not((IntVal(27) == Int('out.dtype'))), Not((IntVal(28) == Int('out.dtype'))), Not((IntVal(29) == Int('out.dtype'))), (Int('end.ndim') == IntVal(0)), (IntVal(0) <= Int('steps')),
                # logspace writes pow(base, exponent) into out; the model's base
                # is 0, so 0**exp = 0 (exp>0), 1 (exp==0) or inf (exp<0). Here the
                # `start` exponent is a Scalar and the `end` exponent is the
                # tensor's item(). For an integer out dtype (0=u8,1=i8,2=i16,
                # 3=i32,4=i64) an inf/nan exponent raises "value cannot be
                # converted without overflow"; uint8 additionally raises on any
                # negative exponent (0**-x = inf, no unsigned wrap).
                # steps==0 computes nothing; steps==1 only uses `start`.
                #
                # start (Scalar) finite when steps>=1:
                Implies(And((Int('steps') >= 1),
                            Or((IntVal(0) == Int('out.dtype')), (IntVal(1) == Int('out.dtype')),
                               (IntVal(2) == Int('out.dtype')), (IntVal(3) == Int('out.dtype')),
                               (IntVal(4) == Int('out.dtype')))),
                        And(Not(Bool('start.is_inf')), Not(Bool('start.is_nan')))),
                # steps==1 checked fill_(pow(base,start)) -> start>=0 for int out:
                Implies(And((IntVal(1) == Int('steps')),
                            Or((IntVal(0) == Int('out.dtype')), (IntVal(1) == Int('out.dtype')),
                               (IntVal(2) == Int('out.dtype')), (IntVal(3) == Int('out.dtype')),
                               (IntVal(4) == Int('out.dtype')))),
                        And((Real('start.real_val') >= 0), (Int('start.int_val') >= 0))),
                # uint8: start>=0 for steps>=1:
                Implies(And((Int('steps') >= 1), (IntVal(0) == Int('out.dtype'))),
                        And((Real('start.real_val') >= 0), (Int('start.int_val') >= 0))),
                # end (Tensor) exponent only used when steps>=2: clamp its data
                # to a finite small range for every out dtype (an inf/nan in the
                # `end` tensor data, injected by the diversity/infnan data mode,
                # makes pow(base,end)=inf/nan which the checked cast rejects),
                # via the concretizer's per-tensor data_lo/data_hi value bounds.
                Implies((Int('steps') >= 2),
                        And((Real('end.data_lo') >= -8), (Real('end.data_hi') <= 8))),
                # uint8: end exponent additionally non-negative (no unsigned wrap).
                Implies(And((Int('steps') >= 2), (IntVal(0) == Int('out.dtype'))),
                        (Real('end.data_lo') >= 0)))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    start = ScalarVar('start')
    end = TensorVar('end')
    out = TensorVar('out')
    return {'start': start, 'end': end, 'out': out}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
