"""Combined + Z3-optimized constraints for _ZN2at6native24structured_ne_Scalar_out4implERKNS_6TensorERKN3c106ScalarES4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from mobile.generator.constraints.model import same_shape, out_is_broadcast


ENTRY = '_ZN2at6native24structured_ne_Scalar_out4implERKNS_6TensorERKN3c106ScalarES4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('other', 'Scalar'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    _out = TensorVar('out'); _self = TensorVar('self')
    out_ok_1 = Or(_out.numel() == 0, same_shape(_out, _self))
    return [
        Not(And(out_ok_1, (Int('self.ndim') >= IntVal(0)), (Int('out.ndim') >= IntVal(0)))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
