"""Combined + Z3-optimized constraints for _ZN2at6native7spdiagsERKNS_6TensorES3_N3c108ArrayRefIlEESt8optionalINS4_6LayoutEE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native7spdiagsERKNS_6TensorES3_N3c108ArrayRefIlEESt8optionalINS4_6LayoutEE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('diagonals', 'Tensor'), ('offsets', 'Tensor'), ('shape', 'int[]'), ('layout', 'int?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    # diagonals_2d.size(1): if ndim==2 -> sizes[1]; if ndim==1 -> unsqueeze(0) so
    # sizes[0] becomes the diagonal length.  Must be >= 1 (empty diagonal length
    # makes nnz_per_diag underflow negative -> at::empty({2,nnz}) crashes with a
    # negative dimension).
    _diag_len = If((IntVal(2) == Int('diagonals.ndim')),
                   Select(Array('diagonals.sizes', IntSort(), IntSort()), IntVal(1)),
                   Select(Array('diagonals.sizes', IntSort(), IntSort()), IntVal(0)))
    # offsets_1d.size(0) == number of diagonals == diagonals_2d.size(0).
    _n_diag = If((IntVal(1) == Int('offsets.ndim')),
                 Select(Array('offsets.sizes', IntSort(), IntSort()), IntVal(0)),
                 IntVal(1))
    return [
        Not(And(Or((IntVal(1) == Int('diagonals.ndim')), (IntVal(2) == Int('diagonals.ndim'))), Or((IntVal(0) == Int('offsets.ndim')), (IntVal(1) == Int('offsets.ndim'))), (IntVal(2) == Int('shape.length')),
            # 2-D output shape, non-degenerate, and wide enough that an in-band
            # offset always lands inside the matrix (shape[1] >= diagonal length).
            (Select(Array('shape.data', IntSort(), IntSort()), IntVal(0)) >= _diag_len),
            (Select(Array('shape.data', IntSort(), IntSort()), IntVal(1)) >= _diag_len),
            (If((IntVal(2) == Int('diagonals.ndim')), Select(Array('diagonals.sizes', IntSort(), IntSort()), IntVal(0)), IntVal(1)) == If((IntVal(1) == Int('offsets.ndim')), Select(Array('offsets.sizes', IntSort(), IntSort()), IntVal(0)), IntVal(1))), (IntVal(4) == Int('offsets.dtype')), Or(Not(Bool('layout.present')), (IntVal(1) == Int('layout.val'))),
            # Diagonal length >= 2 gives a band wide enough to host two distinct
            # offsets (see _n_diag bound below) without a forced collision.
            (_diag_len >= IntVal(2)),
            # Offset VALUES must lie inside the matrix band: for o in [0, diag_len-1]
            # the kernel's nnz_per_diag = min(shape[1],diag_len)-o >= 1, so the
            # at::empty({2,nnz}) never sees a negative dimension.  Clamped on data
            # via the concretizer's [data_lo,data_hi] window (offsets is integer ->
            # ceil(lo)/floor(hi)).  Out-of-band offsets are the dominant negative-nnz
            # crash; in-band is a sound subset of valid offsets.
            (Real('offsets.data_lo') >= IntVal(0)),
            (Real('offsets.data_hi') <= _diag_len - IntVal(1)),
            # Offsets must be pairwise distinct.  Distinctness on data is NOT
            # encodable here (data_lo/data_hi only clamp a contiguous window; the
            # harness fills integer tensors from a tiny pool, so any two offsets
            # collide with probability ~1/band).  A single diagonal is the only
            # structural way to guarantee no duplicate; it remains a sound subset
            # (scalar offset + 1xN/N diagonals are fully valid spdiags inputs).
            (_n_diag == IntVal(1)))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    diagonals = TensorVar('diagonals')
    offsets = TensorVar('offsets')
    shape = IntArrayVar('shape')
    layout = OptVar('layout', Int('layout' + '.val'))
    return {'diagonals': diagonals, 'offsets': offsets, 'shape': shape, 'layout': layout}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
