"""Combined + Z3-optimized constraints for _ZN2at6native8hardtanhERKNS_6TensorERKN3c106ScalarES7_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native8hardtanhERKNS_6TensorERKN3c106ScalarES7_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('min_val', 'Scalar'), ('max_val', 'Scalar')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Or((Int('self.dtype') == IntVal(0)), (Int('self.dtype') == IntVal(1)), (Int('self.dtype') == IntVal(2)), (Int('self.dtype') == IntVal(3)), (Int('self.dtype') == IntVal(4)), (Int('self.dtype') == IntVal(5)), (Int('self.dtype') == IntVal(6)), (Int('self.dtype') == IntVal(7)), (Int('self.dtype') == IntVal(15))), Or(Not((Int('self.dtype') == IntVal(0))), And(If(Or((Int('min_val.dtype') == IntVal(5)), (Int('min_val.dtype') == IntVal(6)), (Int('min_val.dtype') == IntVal(7)), (Int('min_val.dtype') == IntVal(8)), (Int('min_val.dtype') == IntVal(9)), (Int('min_val.dtype') == IntVal(10)), (Int('min_val.dtype') == IntVal(15)), (Int('min_val.dtype') == IntVal(23)), (Int('min_val.dtype') == IntVal(24)), (Int('min_val.dtype') == IntVal(25)), (Int('min_val.dtype') == IntVal(26)), (Int('min_val.dtype') == IntVal(44))), (Real('min_val.real_val') >= RealVal(0)), (Int('min_val.int_val') >= IntVal(0))), If(Or((Int('max_val.dtype') == IntVal(5)), (Int('max_val.dtype') == IntVal(6)), (Int('max_val.dtype') == IntVal(7)), (Int('max_val.dtype') == IntVal(8)), (Int('max_val.dtype') == IntVal(9)), (Int('max_val.dtype') == IntVal(10)), (Int('max_val.dtype') == IntVal(15)), (Int('max_val.dtype') == IntVal(23)), (Int('max_val.dtype') == IntVal(24)), (Int('max_val.dtype') == IntVal(25)), (Int('max_val.dtype') == IntVal(26)), (Int('max_val.dtype') == IntVal(44))), (Real('max_val.real_val') >= RealVal(0)), (Int('max_val.int_val') >= IntVal(0))))))),
    ]


def get_axioms() -> list:
    return []

def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
