"""Combined + Z3-optimized constraints for _ZN2at6native21_scaled_mm_cpu_v2_outERKNS_6TensorES3_N3c108ArrayRefIS1_EENS5_IlEES7_S6_S7_S7_RKSt8optionalIS1_ES8_INS4_10ScalarTypeEES7_bRS1_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
# (scaled_mm out shape modeled inline below)

ENTRY = '_ZN2at6native21_scaled_mm_cpu_v2_outERKNS_6TensorES3_N3c108ArrayRefIS1_EENS5_IlEES7_S6_S7_S7_RKSt8optionalIS1_ES8_INS4_10ScalarTypeEES7_bRS1_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('mat2', 'Tensor'), ('scale_a', 'Tensor[]'), ('recipe_a', 'int[]'), ('swizzle_a', 'int[]'), ('scale_b', 'Tensor[]'), ('recipe_b', 'int[]'), ('swizzle_b', 'int[]'), ('bias', 'Tensor?'), ('out_dtype', 'int?'), ('contraction_dim', 'int[]'), ('use_fast_accum', 'bool'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    # out = self @ mat2 : shape [M, N] = [self.size(0), mat2.size(1)].
    _out = TensorVar('out'); _self = TensorVar('self'); _mat2 = TensorVar('mat2')
    out_ok = Or(
        _out.numel() == IntVal(0),
        And(_out.ndim == IntVal(2),
            _out.size(0) == _self.size(0),
            _out.size(1) == _mat2.size(1)),
    )
    return [
        Not(And(out_ok, (IntVal(2) == Int('self.ndim')), (IntVal(2) == Int('mat2.ndim')), Or((IntVal(23) == Int('self.dtype')), (IntVal(24) == Int('self.dtype'))), Or((IntVal(23) == Int('mat2.dtype')), (IntVal(24) == Int('mat2.dtype'))), (IntVal(0) == Int('contraction_dim.length')), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(1)) == Select(Array('mat2.sizes', IntSort(), IntSort()), IntVal(0))), (IntVal(1) == Int('scale_a.length')), (IntVal(1) == Int('scale_b.length')), (IntVal(1) == Int('recipe_a.length')), (IntVal(1) == Int('recipe_b.length')), (IntVal(0) == Select(Array('recipe_a.data', IntSort(), IntSort()), IntVal(0))), (IntVal(0) == Select(Array('recipe_b.data', IntSort(), IntSort()), IntVal(0))), (IntVal(0) == Int('scale_a[0].ndim')), (IntVal(0) == Int('scale_b[0].ndim')), (IntVal(6) == Int('scale_a[0].dtype')), (IntVal(6) == Int('scale_b[0].dtype')), (IntVal(0) == Int('swizzle_a.length')), (IntVal(0) == Int('swizzle_b.length')), Not(Bool('bias.present')), Not(Bool('out_dtype.present')))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    mat2 = TensorVar('mat2')
    scale_a = TensorListVar('scale_a')
    recipe_a = IntArrayVar('recipe_a')
    swizzle_a = IntArrayVar('swizzle_a')
    scale_b = TensorListVar('scale_b')
    recipe_b = IntArrayVar('recipe_b')
    swizzle_b = IntArrayVar('swizzle_b')
    bias = OptVar('bias', TensorVar('bias' + '.val'))
    out_dtype = OptVar('out_dtype', Int('out_dtype' + '.val'))
    contraction_dim = IntArrayVar('contraction_dim')
    return {'self': self, 'mat2': mat2, 'scale_a': scale_a, 'recipe_a': recipe_a, 'swizzle_a': swizzle_a, 'scale_b': scale_b, 'recipe_b': recipe_b, 'swizzle_b': swizzle_b, 'bias': bias, 'out_dtype': out_dtype, 'contraction_dim': contraction_dim}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
