"""Combined + Z3-optimized constraints for _ZN2at6native32_functional_assert_async_msg_cpuERKNS_6TensorESt17basic_string_viewIcSt11char_traitsIcEES3_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native32_functional_assert_async_msg_cpuERKNS_6TensorESt17basic_string_viewIcSt11char_traitsIcEES3_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('assert_msg', 'str'), ('dep_token', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Or((Int('self.ndim') <= IntVal(0)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(0)) == IntVal(1))), Or((Int('self.ndim') <= IntVal(1)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(1)) == IntVal(1))), Or((Int('self.ndim') <= IntVal(2)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(2)) == IntVal(1))), Or((Int('self.ndim') <= IntVal(3)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(3)) == IntVal(1))), Or((Int('self.ndim') <= IntVal(4)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(4)) == IntVal(1))), Or(And((RealVal(1) <= Real('self.data_lo')), (RealVal(2) <= Real('self.data_hi'))), And(Not((Int('self.dtype') == IntVal(11))), Not((Int('self.dtype') == IntVal(0))), Not((Int('self.dtype') == IntVal(27))), Not((Int('self.dtype') == IntVal(28))), Not((Int('self.dtype') == IntVal(29))), (RealVal(-1) >= Real('self.data_hi')), (RealVal(-2) >= Real('self.data_lo')))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
