"""Combined + Z3-optimized constraints for _ZN2at6native24structured_threshold_out4implERKNS_6TensorERKN3c106ScalarES8_S4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from model import same_shape, out_is_broadcast

ENTRY = '_ZN2at6native24structured_threshold_out4implERKNS_6TensorERKN3c106ScalarES8_S4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('threshold', 'Scalar'), ('value', 'Scalar'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    self = TensorVar('self')
    out = TensorVar('out')
    out_ok = Or(out.numel() == 0, same_shape(out, self))
    # threshold_stub casts the `threshold` and `value` scalars to the result
    # (out) dtype. For small integer out dtypes a too-large/fractional scalar
    # raises "value cannot be converted to type ... without overflow". Bound both
    # scalars to the integer range of out.dtype (free for float/int64 out).
    _sd = Int('self.dtype')
    _od = Int('out.dtype')
    _thr = ScalarVar('threshold')
    _val = ScalarVar('value')
    def _in_int_range_for(dt, sc):
        lo = If(dt == IntVal(0), RealVal(0),                 # uint8 [0,255]
             If(dt == IntVal(1), RealVal(-128),              # int8
             If(dt == IntVal(2), RealVal(-32768),            # int16
             If(dt == IntVal(3), RealVal(-2147483648),       # int32
                RealVal(0)))))
        hi = If(dt == IntVal(0), RealVal(255),
             If(dt == IntVal(1), RealVal(127),
             If(dt == IntVal(2), RealVal(32767),
             If(dt == IntVal(3), RealVal(2147483647),
                RealVal(0)))))
        # only constrain when this dtype is a small integer dtype; else vacuously ok
        small_int = Or(dt == IntVal(0), dt == IntVal(1), dt == IntVal(2), dt == IntVal(3))
        return Or(Not(small_int),
                  And(sc.real_val >= lo, sc.real_val <= hi,
                      ToReal(sc.int_val) >= lo, ToReal(sc.int_val) <= hi,
                      Not(sc.is_inf), Not(sc.is_nan)))
    # The scalars are cast both to self's dtype (compute) and out's dtype (store).
    _scalar_ok = And(_in_int_range_for(_sd, _thr), _in_int_range_for(_sd, _val),
                     _in_int_range_for(_od, _thr), _in_int_range_for(_od, _val))
    return [
        Not(And((Int('self.ndim') >= IntVal(0)), Or((Int('self.dtype') == IntVal(0)), (Int('self.dtype') == IntVal(1)), (Int('self.dtype') == IntVal(2)), (Int('self.dtype') == IntVal(3)), (Int('self.dtype') == IntVal(4)), (Int('self.dtype') == IntVal(5)), (Int('self.dtype') == IntVal(6)), (Int('self.dtype') == IntVal(7)), (Int('self.dtype') == IntVal(15))), Or((Int('out.dtype') == IntVal(0)), (Int('out.dtype') == IntVal(1)), (Int('out.dtype') == IntVal(2)), (Int('out.dtype') == IntVal(3)), (Int('out.dtype') == IntVal(4)), (Int('out.dtype') == IntVal(5)), (Int('out.dtype') == IntVal(6)), (Int('out.dtype') == IntVal(7)), (Int('out.dtype') == IntVal(15)), (Int('out.dtype') == IntVal(8)), (Int('out.dtype') == IntVal(9)), (Int('out.dtype') == IntVal(10))), Not(And(Or((Int('self.dtype') == IntVal(5)), (Int('self.dtype') == IntVal(6)), (Int('self.dtype') == IntVal(7)), (Int('self.dtype') == IntVal(15))), Or((Int('out.dtype') == IntVal(0)), (Int('out.dtype') == IntVal(1)), (Int('out.dtype') == IntVal(2)), (Int('out.dtype') == IntVal(3)), (Int('out.dtype') == IntVal(4))))), out_ok, _scalar_ok)),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
