"""Combined + Z3-optimized constraints for _ZN2at6native41fake_quantize_per_tensor_affine_cachemaskERKNS_6TensorEdlll.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native41fake_quantize_per_tensor_affine_cachemaskERKNS_6TensorEdlll (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('scale', 'float'), ('zero_point', 'int'), ('quant_min', 'int'), ('quant_max', 'int')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('zero_point') >= Int('quant_min')), (Int('zero_point') <= Int('quant_max')), Or((Int('self.dtype') == IntVal(5)), (Int('self.dtype') == IntVal(6)), (Int('self.dtype') == IntVal(7)), (Int('self.dtype') == IntVal(15))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
