"""Combined + Z3-optimized constraints for _ZN2at6native12hardtanh_outERKNS_6TensorERKN3c106ScalarES7_RS1_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar, same_shape

ENTRY = '_ZN2at6native12hardtanh_outERKNS_6TensorERKN3c106ScalarES7_RS1_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('min_val', 'Scalar'), ('max_val', 'Scalar'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    # When self is an integral dtype, hardtanh_out calls min.toLong()/max.toLong()
    # (Activation.cpp:447-448). A non-finite scalar (inf/nan from the infnan edge
    # mode) overflows int64 conversion -> "value cannot be converted to type
    # int64_t without overflow". Require the bound scalars to be finite for the
    # integral case (codes 0,1,2,3,4,27,28,29 = u8,i8,i16,i32,i64,uint16/32/64).
    _self_integral = Or(*[IntVal(c) == Int('self.dtype') for c in (0, 1, 2, 3, 4, 27, 28, 29)])
    _scalars_finite = And(Not(ScalarVar('min_val').is_inf), Not(ScalarVar('min_val').is_nan),
                          Not(ScalarVar('max_val').is_inf), Not(ScalarVar('max_val').is_nan))
    return [
        Not(And(Or(TensorVar('out').numel() == 0, same_shape(TensorVar('out'), TensorVar('self'))), (Int('out.dtype') == Int('self.dtype')), Not((IntVal(11) == Int('self.dtype'))), Not(And((IntVal(0) == Int('self.dtype')), Or(Not((IntVal(0) <= Int('min_val.int_val'))), Not((RealVal(0) <= Real('min_val.real_val'))), Not((IntVal(0) <= Int('max_val.int_val'))), Not((RealVal(0) <= Real('max_val.real_val')))))), Not((IntVal(8) == Int('self.dtype'))), Not((IntVal(9) == Int('self.dtype'))), Not((IntVal(10) == Int('self.dtype'))), Not((IntVal(23) == Int('self.dtype'))), Not((IntVal(24) == Int('self.dtype'))), Not((IntVal(25) == Int('self.dtype'))), Not((IntVal(26) == Int('self.dtype'))), Not((IntVal(44) == Int('self.dtype'))), Not((IntVal(27) == Int('self.dtype'))), Not((IntVal(28) == Int('self.dtype'))), Not((IntVal(29) == Int('self.dtype'))), Implies(_self_integral, _scalars_finite))),
    ]


def get_axioms() -> list:
    # HAND-ADDED (not from combine_constraints.py — keep across re-vendoring).
    # This op's CPU kernel raises NotImplementedError for every float8 dtype, e.g.
    #   NotImplementedError: "hardtanh.out" not implemented for 'Float8_e5m2'
    # so a float8 call is invalid however well-shaped it is. Stated as an axiom because
    # axioms are asserted directly, while get_constraints() describes ERROR paths and is
    # negated by the harness. Verified by probing every core op with float8 vs float32
    # inputs: 75 of 221 accept float32 and reject float8.
    _FLOAT8 = (23, 24, 25, 26, 44)   # model.FLOAT8_DTYPES
    return [
            Not(Or(*(Int('self.dtype') == IntVal(c) for c in _FLOAT8))),
            Not(Or(*(Int('out.dtype') == IntVal(c) for c in _FLOAT8))),
    ]


def get_vars() -> dict:
    self = TensorVar('self')
    min_val = ScalarVar('min_val')
    max_val = ScalarVar('max_val')
    out = TensorVar('out')
    return {'self': self, 'min_val': min_val, 'max_val': max_val, 'out': out}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
