"""Combined + Z3-optimized constraints for _ZN2at6native22structured_all_all_out4implERKNS_6TensorES4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from mobile.generator.constraints.model import same_shape, out_is_broadcast

ENTRY = '_ZN2at6native22structured_all_all_out4implERKNS_6TensorES4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def _get_constraints_orig() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('self.ndim') >= IntVal(0)), Or((Int('out.dtype') == IntVal(11)), (Int('out.dtype') == IntVal(0))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s


def get_constraints() -> list:
    # OUTPUT-SHAPE FIX: all() full reduction -> 0-dim scalar out (numel 1, ndim 0).
    # resize_output hard-errors on wrong non-empty out; require empty or exact.
    out = TensorVar('out')
    out_ok = Or(out.numel() == 0, out.ndim == 0)
    return [Or(c, Not(out_ok)) for c in _get_constraints_orig()]
