#!/usr/bin/env python3
"""gen_custom_ops_yaml.py — split backends/cadence/aot/functions.yaml into its CUSTOM-op half.

Why this exists: the in-tree `cadence_ops_lib` is codegen'd from the WHOLE
`backends/cadence/aot/functions.yaml`, which mixes two kinds of entry:

  - op:   <aten op>.out      # 36 ATen ops, all mapped to PORTABLE kernels (torch::executor::*)
  - func: cadence::<op>.out  # 60 cadence:: custom DSP ops (impl::generic::* on the host)

Linking that lib gives the runner only those 36 ATen ops, so any graph touching an ATen op
outside the list fails to load with `Missing operator: aten::<op>.out` — 72.5% of the
corpus_v5 corpus. We cannot simply add `portable_ops_lib` on top: both libs would register
the 36 overlapping ATen kernels and the runtime aborts at init on the duplicate.

So we emit a yaml with ONLY the `- func: cadence::` entries and codegen a slim ops lib from
it. The runner then links that slim lib PLUS the prebuilt `portable_ops_lib` (all 200 ATen
ops + the dim_order_ops). The two are disjoint by construction — `cadence::` vs
`aten::`/`dim_order_ops::` — so nothing is registered twice.

Dropping the 36 `- op:` entries loses nothing: every one names a `torch::executor::` (i.e.
portable) kernel and every one is present in kernels/portable/functions.yaml, so
portable_ops_lib provides the identical kernel. Verified 2026-07-28.

    gen_custom_ops_yaml.py <in functions.yaml> <out custom_ops.yaml>
"""
from __future__ import annotations

import re
import sys


def split_entries(text: str) -> list[str]:
    """Split a functions.yaml into its top-level `- op:` / `- func:` entries, keeping the
    comment/blank lines that precede each one attached to it."""
    return re.split(r"\n(?=- (?:op|func):)", text)


def main() -> int:
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <in functions.yaml> <out custom_ops.yaml>")
    src, dst = sys.argv[1], sys.argv[2]
    entries = split_entries(open(src).read())

    kept, dropped = [], []
    for e in entries:
        if e.lstrip().startswith("- func:"):
            kept.append(e)
        elif e.lstrip().startswith("- op:"):
            dropped.append(re.match(r"\s*- op:\s*(\S+)", e).group(1))
        # else: the leading license/comment preamble — not an entry, skip it

    if not kept:
        sys.exit(f"FATAL: no `- func:` custom-op entries found in {src}")

    header = (
        "# GENERATED by mobile/cadence_client/gen_custom_ops_yaml.py — do not edit.\n"
        f"# source: {src}\n"
        "#\n"
        "# The cadence:: CUSTOM ops only. The ATen half of the source yaml is deliberately\n"
        "# omitted: those kernels come from the prebuilt portable_ops_lib instead, which\n"
        "# covers all 200 portable ATen ops rather than the source yaml's 36. Keeping both\n"
        "# would double-register the overlap and abort the runtime at init.\n"
        f"# dropped {len(dropped)} ATen entries: {', '.join(sorted(dropped))}\n"
        "\n"
    )
    with open(dst, "w") as f:
        f.write(header + "\n".join(kept).rstrip() + "\n")
    print(f"{dst}: kept {len(kept)} cadence:: custom ops, dropped {len(dropped)} aten ops")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
