#!/usr/bin/env python3
"""gen_portable_complement_yaml.py — emit the portable ops NOT claimed by a cadence yaml.

Why this exists (the hifi target). For the `generic` target we can hand the whole ATen half of
the registry to the prebuilt `portable_ops_lib` and keep only the `cadence::` custom ops from
executorch's yaml — see gen_custom_ops_yaml.py. That works because generic's ATen entries all
name plain `torch::executor::` (portable) kernels, so portable_ops_lib provides identical code.

For `hifi` that reasoning BREAKS. `backends/cadence/aot/functions_hifi.yaml` maps 57 ATen ops to
`impl::HiFi::*` kernels — hand-vectorised HiFi4/nnlib microkernels (add, mul, atan2, bmm, mean,
softmax, pow, sigmoid, tanh, ...). Those are precisely the code under test. Taking the ATen half
from portable_ops_lib would silently run the PORTABLE kernels instead and test nothing new.

So for hifi we keep executorch's in-tree `cadence_ops_lib` (codegen'd from functions_hifi.yaml,
covering 57 ATen + 56 cadence:: ops) and supplement it with the COMPLEMENT of the portable
registry: every entry of kernels/portable/functions.yaml whose op is *not* already claimed by
functions_hifi.yaml (143 ATen ops + the dim_order_ops entries). The two registries are then
disjoint by construction, so nothing is registered twice — a duplicate registration aborts the
runtime at init.

Note portable_ops_lib is codegen'd from kernels/portable/functions.yaml ALONE (verified in
kernels/portable/CMakeLists.txt); custom_ops.yaml / allclose is not part of it, so neither is it
part of the complement.

    gen_portable_complement_yaml.py <portable functions.yaml> <cadence functions_hifi.yaml> <out.yaml>
"""

from __future__ import annotations

import re
import sys


def split_entries(text: str) -> list[str]:
    """Split a functions.yaml into its top-level `- op:` / `- func:` entries, keeping the
    comment/blank lines that precede each one attached to it."""
    return re.split(r"\n(?=- (?:op|func):)", text)


def entry_key(entry: str) -> tuple[str, str] | None:
    """('op'|'func', name) for an entry, or None for the leading license/comment preamble.
    A `- func:` entry carries a full signature; the name is everything before the '('."""
    m = re.match(r"\s*- (op|func):\s*(\S+)", entry)
    if not m:
        return None
    kind, name = m.group(1), m.group(2)
    return kind, name.split("(", 1)[0]


def main() -> int:
    if len(sys.argv) != 4:
        sys.exit(f"usage: {sys.argv[0]} <portable functions.yaml> <cadence yaml> <out.yaml>")
    portable_path, cadence_path, dst = sys.argv[1], sys.argv[2], sys.argv[3]

    claimed = set()
    for entry in split_entries(open(cadence_path).read()):
        key = entry_key(entry)
        if key:
            claimed.add(key)

    # Sanity: the cadence yaml's custom half must live in the cadence:: namespace, otherwise it
    # could collide with a portable `- func:` (dim_order_ops) in a way this filter would miss.
    stray = [n for k, n in claimed if k == "func" and not n.startswith("cadence::")]
    if stray:
        sys.exit(f"FATAL: non-cadence:: func entries in {cadence_path}: {stray}")

    kept, dropped = [], []
    for entry in split_entries(open(portable_path).read()):
        key = entry_key(entry)
        if key is None:
            continue  # leading preamble
        if key in claimed:
            dropped.append(key[1])
        else:
            kept.append(entry)

    if not kept:
        sys.exit(f"FATAL: complement is empty — {portable_path} fully claimed by {cadence_path}?")
    if not dropped:
        sys.exit(
            f"FATAL: nothing dropped — {cadence_path} claims none of {portable_path}'s ops, "
            "so the two registries would not actually overlap. Check the inputs."
        )

    header = (
        "# GENERATED by mobile/cadence_client/gen_portable_complement_yaml.py — do not edit.\n"
        f"# portable source: {portable_path}\n"
        f"# excluded by:     {cadence_path}\n"
        "#\n"
        "# The portable ops NOT claimed by the cadence yaml. Linked ALONGSIDE the in-tree\n"
        "# cadence_ops_lib so ATen coverage stays complete while the ops the cadence yaml does\n"
        "# claim keep running their HiFi (impl::HiFi::*) kernels — the code under test.\n"
        f"# kept {len(kept)} entries; dropped {len(dropped)} claimed by the cadence yaml:\n"
        f"#   {', '.join(sorted(dropped))}\n"
        "\n"
    )
    with open(dst, "w") as f:
        f.write(header + "\n".join(kept).rstrip() + "\n")
    print(f"{dst}: kept {len(kept)} portable entries, dropped {len(dropped)} claimed by cadence")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
