"""Combined + Z3-optimized constraints for _ZN2at6native15_cdist_backwardERKNS_6TensorES3_S3_dS3_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native15_cdist_backwardERKNS_6TensorES3_S3_dS3_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('grad', 'Tensor'), ('x1', 'Tensor'), ('x2', 'Tensor'), ('p', 'float'), ('cdist', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Or((Int('x1.dtype') == IntVal(6)), (Int('x1.dtype') == IntVal(7))), (Int('grad.dtype') == Int('x1.dtype')), (Int('x2.dtype') == Int('x1.dtype')), (Int('cdist.dtype') == Int('x1.dtype')), (Int('x1.ndim') >= IntVal(2)), (Int('x2.ndim') >= IntVal(2)), Or((Select(Array('x1.sizes', IntSort(), IntSort()), (IntVal(-3) + Int('x1.ndim'))) == IntVal(1)), (Select(Array('x2.sizes', IntSort(), IntSort()), (IntVal(-3) + Int('x2.ndim'))) == IntVal(1)), (Select(Array('x1.sizes', IntSort(), IntSort()), (IntVal(-3) + Int('x1.ndim'))) == Select(Array('x2.sizes', IntSort(), IntSort()), (IntVal(-3) + Int('x2.ndim')))), Not(And((Int('x1.ndim') >= IntVal(3)), (Int('x2.ndim') >= IntVal(3))))), Or((Select(Array('x1.sizes', IntSort(), IntSort()), (IntVal(-4) + Int('x1.ndim'))) == IntVal(1)), (Select(Array('x2.sizes', IntSort(), IntSort()), (IntVal(-4) + Int('x2.ndim'))) == IntVal(1)), (Select(Array('x1.sizes', IntSort(), IntSort()), (IntVal(-4) + Int('x1.ndim'))) == Select(Array('x2.sizes', IntSort(), IntSort()), (IntVal(-4) + Int('x2.ndim')))), Not(And((Int('x1.ndim') >= IntVal(4)), (Int('x2.ndim') >= IntVal(4))))), Or((Select(Array('x1.sizes', IntSort(), IntSort()), (IntVal(-5) + Int('x1.ndim'))) == IntVal(1)), (Select(Array('x2.sizes', IntSort(), IntSort()), (IntVal(-5) + Int('x2.ndim'))) == IntVal(1)), (Select(Array('x1.sizes', IntSort(), IntSort()), (IntVal(-5) + Int('x1.ndim'))) == Select(Array('x2.sizes', IntSort(), IntSort()), (IntVal(-5) + Int('x2.ndim')))), Not(And((Int('x1.ndim') >= IntVal(5)), (Int('x2.ndim') >= IntVal(5))))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    grad = TensorVar('grad')
    x1 = TensorVar('x1')
    x2 = TensorVar('x2')
    cdist = TensorVar('cdist')
    return {'grad': grad, 'x1': x1, 'x2': x2, 'cdist': cdist}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
