"""Combined + Z3-optimized constraints for _ZN2at6native16fft_ihfft_symintERKNS_6TensorESt8optionalIN3c106SymIntEElS4_ISt17basic_string_viewIcSt11char_traitsIcEEE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native16fft_ihfft_symintERKNS_6TensorESt8optionalIN3c106SymIntEElS4_ISt17basic_string_viewIcSt11char_traitsIcEEE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('n', 'int?'), ('dim', 'int'), ('norm', 'str?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Not((Int('self.dtype') == IntVal(8))), Not((Int('self.dtype') == IntVal(9))), Not((Int('self.dtype') == IntVal(10))), Not((Int('self.dtype') == IntVal(5))), Not((Int('self.dtype') == IntVal(15))), Not((Int('self.dtype') == IntVal(23))), Not((Int('self.dtype') == IntVal(24))), Not((Int('self.dtype') == IntVal(25))), Not((Int('self.dtype') == IntVal(26))), Not((Int('self.dtype') == IntVal(44))), (Int('self.ndim') >= IntVal(1)), (Int('dim') >= (IntVal(-1) * Int('self.ndim'))), Not((Int('self.ndim') <= Int('dim'))), Or(Not(Bool('n.present')), (Int('n.val') >= IntVal(1))), Or((Int('self.ndim') <= IntVal(0)), Not((Select(Array('self.sizes', IntSort(), IntSort()), IntVal(0)) <= IntVal(0)))), Or((Int('self.ndim') <= IntVal(1)), Not((Select(Array('self.sizes', IntSort(), IntSort()), IntVal(1)) <= IntVal(0)))), Or((Int('self.ndim') <= IntVal(2)), Not((Select(Array('self.sizes', IntSort(), IntSort()), IntVal(2)) <= IntVal(0)))), Or((Int('self.ndim') <= IntVal(3)), Not((Select(Array('self.sizes', IntSort(), IntSort()), IntVal(3)) <= IntVal(0)))), Or((Int('self.ndim') <= IntVal(4)), Not((Select(Array('self.sizes', IntSort(), IntSort()), IntVal(4)) <= IntVal(0)))), Not(Bool('norm.present')))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    return {'self': self}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
