"""Combined + Z3-optimized constraints for _ZN2at6native31_functional_sym_constrain_rangeERKN3c106ScalarESt8optionalIlES6_RKNS_6TensorE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native31_functional_sym_constrain_rangeERKN3c106ScalarESt8optionalIlES6_RKNS_6TensorE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('size', 'Scalar'), ('min', 'int?'), ('max', 'int?'), ('dep_token', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Not(Bool('size.is_inf')), Not(Bool('size.is_nan')), Or(Not(Bool('min.present')), And((IntVal(-9223372036854775808) <= Int('min.val')), (IntVal(9223372036854775807) >= Int('min.val')))), Or(Not(Bool('max.present')), And((IntVal(-9223372036854775808) <= Int('max.val')), (IntVal(9223372036854775807) >= Int('max.val')))), (If(Bool('max.present'), Int('max.val'), IntVal(9223372036854775807)) >= If(Bool('min.present'), Int('min.val'), IntVal(-9223372036854775808))), Or(Not(Bool('min.present')), (If(Bool('min.present'), Int('min.val'), IntVal(-9223372036854775808)) <= If(Or((Int('size.dtype') == IntVal(5)), (Int('size.dtype') == IntVal(6)), (Int('size.dtype') == IntVal(7)), (Int('size.dtype') == IntVal(15)), (Int('size.dtype') == IntVal(23)), (Int('size.dtype') == IntVal(24)), (Int('size.dtype') == IntVal(25)), (Int('size.dtype') == IntVal(26)), (Int('size.dtype') == IntVal(44)), (Int('size.dtype') == IntVal(8)), (Int('size.dtype') == IntVal(9)), (Int('size.dtype') == IntVal(10))), ToInt(Real('size.real_val')), Int('size.int_val')))), Or(Not(Bool('max.present')), (If(Or((Int('size.dtype') == IntVal(5)), (Int('size.dtype') == IntVal(6)), (Int('size.dtype') == IntVal(7)), (Int('size.dtype') == IntVal(15)), (Int('size.dtype') == IntVal(23)), (Int('size.dtype') == IntVal(24)), (Int('size.dtype') == IntVal(25)), (Int('size.dtype') == IntVal(26)), (Int('size.dtype') == IntVal(44)), (Int('size.dtype') == IntVal(8)), (Int('size.dtype') == IntVal(9)), (Int('size.dtype') == IntVal(10))), ToInt(Real('size.real_val')), Int('size.int_val')) <= If(Bool('max.present'), Int('max.val'), IntVal(9223372036854775807)))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
