"""Combined + Z3-optimized constraints for _ZN2at6native4sub_ERNS_6TensorERKN3c106ScalarES6_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native4sub_ERNS_6TensorERKN3c106ScalarES6_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('other', 'Scalar'), ('alpha', 'Scalar')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('other.dtype') != IntVal(11)), Not((Int('self.dtype') == IntVal(11))), Not((Int('self.dtype') == IntVal(23))), Not((Int('self.dtype') == IntVal(24))), Not((Int('self.dtype') == IntVal(25))), Not((Int('self.dtype') == IntVal(26))), Not((Int('self.dtype') == IntVal(44))), Not((Int('self.dtype') == IntVal(27))), Not((Int('self.dtype') == IntVal(28))), Not((Int('self.dtype') == IntVal(29))), Not((Int('alpha.dtype') == IntVal(11))), Or((Int('alpha.dtype') == IntVal(0)), (Int('alpha.dtype') == IntVal(1)), (Int('alpha.dtype') == IntVal(2)), (Int('alpha.dtype') == IntVal(3)), (Int('alpha.dtype') == IntVal(4)), (Int('alpha.dtype') == IntVal(27)), (Int('alpha.dtype') == IntVal(28)), (Int('alpha.dtype') == IntVal(29)), Not(Or((Int('self.dtype') == IntVal(0)), (Int('self.dtype') == IntVal(1)), (Int('self.dtype') == IntVal(2)), (Int('self.dtype') == IntVal(3)), (Int('self.dtype') == IntVal(4))))), Or((Int('self.dtype') == IntVal(8)), (Int('self.dtype') == IntVal(9)), (Int('self.dtype') == IntVal(10)), Not(Or((Int('alpha.dtype') == IntVal(8)), (Int('alpha.dtype') == IntVal(9)), (Int('alpha.dtype') == IntVal(10))))), Or((Int('other.dtype') == IntVal(0)), (Int('other.dtype') == IntVal(1)), (Int('other.dtype') == IntVal(2)), (Int('other.dtype') == IntVal(3)), (Int('other.dtype') == IntVal(4)), (Int('other.dtype') == IntVal(27)), (Int('other.dtype') == IntVal(28)), (Int('other.dtype') == IntVal(29)), Not(Or((Int('self.dtype') == IntVal(0)), (Int('self.dtype') == IntVal(1)), (Int('self.dtype') == IntVal(2)), (Int('self.dtype') == IntVal(3)), (Int('self.dtype') == IntVal(4))))), Or((Int('self.dtype') == IntVal(8)), (Int('self.dtype') == IntVal(9)), (Int('self.dtype') == IntVal(10)), Not(Or((Int('other.dtype') == IntVal(8)), (Int('other.dtype') == IntVal(9)), (Int('other.dtype') == IntVal(10))))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    other = ScalarVar('other')
    alpha = ScalarVar('alpha')
    return {'self': self, 'other': other, 'alpha': alpha}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
