"""Combined + Z3-optimized constraints for _ZN2at6native12linspace_outERKN3c106ScalarES4_lRNS_6TensorE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native12linspace_outERKN3c106ScalarES4_lRNS_6TensorE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('start', 'Scalar'), ('end', 'Scalar'), ('steps', 'int'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def _val_in_dtype_range(v, dt):
    # linspace casts each computed element to the output dtype; a start/end whose
    # value (or any interpolated point between them) is out of the dtype's
    # representable range raises "value cannot be converted to type X without
    # overflow".  Bound v to the output dtype's range so the cast never overflows.
    # (Per-dtype RealVal limits; integer dtypes use their min/max, float dtypes
    # their finite max magnitude.)
    return And(
        If(dt == IntVal(0),  And(v >= RealVal(0),            v <= RealVal(255)),            # uint8
        If(dt == IntVal(1),  And(v >= RealVal(-128),         v <= RealVal(127)),            # int8
        If(dt == IntVal(2),  And(v >= RealVal(-32768),       v <= RealVal(32767)),          # int16
        If(dt == IntVal(3),  And(v >= RealVal(-2147483648),  v <= RealVal(2147483647)),     # int32
        If(dt == IntVal(4),  And(v >= RealVal(-9223372036854775808), v <= RealVal(9223372036854775807)),  # int64
        # Float / complex outputs: PyTorch only rejects finite values that exceed
        # the IEEE max (a band the random concretizer effectively never hits in
        # valid sampling), while over-constraint sampling will deliberately probe
        # any hard cap and round across it.  Leaving these UNBOUNDED keeps the
        # constraint tight (no spurious boundary rejections); inf/nan are already
        # allowed for float outputs (forbidden only for integer outputs above).
                             BoolVal(True),
        )))))
    )


def _int_val_in_dtype_range(v, dt):
    # An INTEGER scalar fed to an integer output is range-checked against the
    # output dtype, but uint8 additionally accepts the signed-negative range
    # ([-255,255] empirically — the unsigned overflow check admits the two's-
    # complement window).  All other integer dtypes use their plain signed range.
    return And(
        If(dt == IntVal(0),  And(v >= RealVal(-255),         v <= RealVal(255)),            # uint8 (int-scalar quirk)
        If(dt == IntVal(1),  And(v >= RealVal(-128),         v <= RealVal(127)),            # int8
        If(dt == IntVal(2),  And(v >= RealVal(-32768),       v <= RealVal(32767)),          # int16
        If(dt == IntVal(3),  And(v >= RealVal(-2147483648),  v <= RealVal(2147483647)),     # int32
        If(dt == IntVal(4),  And(v >= RealVal(-9223372036854775808), v <= RealVal(9223372036854775807)),  # int64
                             BoolVal(True),                                                  # float/complex out: int-scalar always fine
        )))))
    )


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    dt = Int('out.dtype')
    int_out = Or(*[dt == IntVal(c) for c in (0, 1, 2, 3, 4)])
    # steps==0 computes no elements (no cast, any value OK); steps==1 uses only
    # `start`; steps>=2 casts both endpoints (interior points lie within
    # [start,end]).  inf/nan are valid for float/complex outputs but overflow
    # integer outputs (codes 0..4: u8,i8,i16,i32,i64).
    # Which value var the concretizer actually reads depends on the scalar's own
    # dtype: floating/complex scalars use real_val, all others use int_val.  Only
    # bound the active one so an unconstrained sibling var can't spuriously trip
    # the range check.  Scalar floating dtypes: 5,6,7,8,15,23,24,25,26,44;
    # complex: 8(CHalf),9,10.  (CHalf 8 in both — uses real_val either way.)
    def _scalar_val_ok(name):
        sdt = Int(f'{name}.dtype')
        uses_real = Or(*[sdt == IntVal(c) for c in (5,6,7,8,9,10,15,23,24,25,26,44)])
        return And(
            Implies(uses_real, _val_in_dtype_range(Real(f'{name}.real_val'), dt)),
            Implies(Not(uses_real), _int_val_in_dtype_range(ToReal(Int(f'{name}.int_val')), dt)),
        )
    start_ok = And(
        Implies(int_out, And(Not(Bool('start.is_inf')), Not(Bool('start.is_nan')))),
        _scalar_val_ok('start'),
    )
    end_ok = And(
        Implies(int_out, And(Not(Bool('end.is_inf')), Not(Bool('end.is_nan')))),
        _scalar_val_ok('end'),
    )
    return [
        Not(And((Int('steps') >= IntVal(0)), Or((Int('steps') <= IntVal(1)), And(Not((Int('out.dtype') == IntVal(11))), Not((Int('out.dtype') == IntVal(8))), Not((Int('out.dtype') == IntVal(23))), Not((Int('out.dtype') == IntVal(24))), Not((Int('out.dtype') == IntVal(25))), Not((Int('out.dtype') == IntVal(26))), Not((Int('out.dtype') == IntVal(44))), Not((Int('out.dtype') == IntVal(27))), Not((Int('out.dtype') == IntVal(28))), Not((Int('out.dtype') == IntVal(29))))),
            Implies(Int('steps') >= IntVal(1), start_ok),
            Implies(Int('steps') >= IntVal(2), end_ok),
        )),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
