"""Combined + Z3-optimized constraints for _ZN2at6native12_histogramddERKNS_6TensorEN3c108ArrayRefIS1_EERKSt8optionalIS1_Eb.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native12_histogramddERKNS_6TensorEN3c108ArrayRefIS1_EERKSt8optionalIS1_Eb (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('bins', 'int[]'), ('range', 'float[]?'), ('weight', 'Tensor?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('self.ndim') >= IntVal(2)), Or((IntVal(6) == Int('self.dtype')), (IntVal(7) == Int('self.dtype'))), (Int('bins.length') == Select(Array('self.sizes', IntSort(), IntSort()), (IntVal(-1) + Int('self.ndim')))), Not(Bool('range.present')), Or((Int('bins.length') <= IntVal(0)), (Select(Array('bins.data', IntSort(), IntSort()), IntVal(0)) >= IntVal(1))), Or((Int('bins.length') <= IntVal(1)), (Select(Array('bins.data', IntSort(), IntSort()), IntVal(1)) >= IntVal(1))), Or((Int('bins.length') <= IntVal(2)), (Select(Array('bins.data', IntSort(), IntSort()), IntVal(2)) >= IntVal(1))), Or((Int('bins.length') <= IntVal(3)), (Select(Array('bins.data', IntSort(), IntSort()), IntVal(3)) >= IntVal(1))), Or((Int('bins.length') <= IntVal(4)), (Select(Array('bins.data', IntSort(), IntSort()), IntVal(4)) >= IntVal(1))), Or(Not(Bool('weight.present')), And((Int('weight.val.dtype') == Int('self.dtype')), (Int('weight.val.ndim') == (IntVal(-1) + Int('self.ndim'))), Or((Int('weight.val.ndim') <= IntVal(0)), (Select(Array('weight.val.sizes', IntSort(), IntSort()), IntVal(0)) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(0)))), Or((Int('weight.val.ndim') <= IntVal(1)), (Select(Array('weight.val.sizes', IntSort(), IntSort()), IntVal(1)) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(1)))), Or((Int('weight.val.ndim') <= IntVal(2)), (Select(Array('weight.val.sizes', IntSort(), IntSort()), IntVal(2)) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(2)))), Or((Int('weight.val.ndim') <= IntVal(3)), (Select(Array('weight.val.sizes', IntSort(), IntSort()), IntVal(3)) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(3)))), Or((Int('weight.val.ndim') <= IntVal(4)), (Select(Array('weight.val.sizes', IntSort(), IntSort()), IntVal(4)) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(4)))))), And((Real('self.data_lo') >= RealVal(-1e30)), (Real('self.data_hi') <= RealVal(1e30))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    bins = IntArrayVar('bins')
    range = OptVar('range', Int('range' + '.val'))
    weight = OptVar('weight', TensorVar('weight' + '.val'))
    return {'self': self, 'bins': bins, 'range': range, 'weight': weight}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
