"""Combined + Z3-optimized constraints for _ZN2at6native29structured_round_decimals_out4implERKNS_6TensorElS4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from mobile.generator.constraints.model import same_shape, out_is_broadcast

ENTRY = '_ZN2at6native29structured_round_decimals_out4implERKNS_6TensorElS4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('decimals', 'int'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    _ref = TensorVar('self'); _out = TensorVar('out')
    out_ok = Or(_out.numel() == 0, same_shape(_out, _ref))
    return [
        Not(And(Or((IntVal(5) == Int('self.dtype')), (IntVal(6) == Int('self.dtype')), (IntVal(7) == Int('self.dtype')), (IntVal(15) == Int('self.dtype'))), (Int('out.dtype') == Int('self.dtype')), out_ok)),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    out = TensorVar('out')
    return {'self': self, 'out': out}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
