"""Combined + Z3-optimized constraints for _ZN2at6native22_test_optional_intlistERKNS_6TensorEN3c1016OptionalArrayRefIlEE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native22_test_optional_intlistERKNS_6TensorEN3c1016OptionalArrayRefIlEE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('values', 'Tensor'), ('addends', 'int[]?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(Or(Not(Bool('addends.present')), And(Bool('addends.present'), (Int('values.ndim') == IntVal(1)), (Int('values.dtype') == IntVal(3)), (Int('addends.val.length') >= Select(Array('values.sizes', IntSort(), IntSort()), IntVal(0)))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    values = TensorVar('values')
    addends = OptVar('addends', IntArrayVar('addends' + '.val'))
    return {'values': values, 'addends': addends}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
