"""Combined + Z3-optimized constraints for _ZN2at6native18transpose_copy_intERKNS_6TensorEll.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native18transpose_copy_intERKNS_6TensorEll (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('dim0', 'int'), ('dim1', 'int')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('dim0') >= (IntVal(-1) * If((IntVal(1) <= Int('self.ndim')), Int('self.ndim'), IntVal(1)))), Not((If((IntVal(1) <= Int('self.ndim')), Int('self.ndim'), IntVal(1)) <= Int('dim0'))), (Int('dim1') >= (IntVal(-1) * If((IntVal(1) <= Int('self.ndim')), Int('self.ndim'), IntVal(1)))), Not((If((IntVal(1) <= Int('self.ndim')), Int('self.ndim'), IntVal(1)) <= Int('dim1'))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
