"""Combined + Z3-optimized constraints for _ZN2at6native11set_tensor_ERNS_6TensorERKS1_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native11set_tensor_ERNS_6TensorERKS1_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('source', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('self.ndim') >= IntVal(0)), Not(And((Int('self.ndim') == IntVal(0)), (Int('source.ndim') == IntVal(0)), Not((If(Or((Int('self.dtype') == IntVal(4)), (Int('self.dtype') == IntVal(7)), (Int('self.dtype') == IntVal(29)), (Int('self.dtype') == IntVal(9))), IntVal(8), If((Int('self.dtype') == IntVal(10)), IntVal(16), If(Or((Int('self.dtype') == IntVal(3)), (Int('self.dtype') == IntVal(6)), (Int('self.dtype') == IntVal(28)), (Int('self.dtype') == IntVal(8))), IntVal(4), If(Or((Int('self.dtype') == IntVal(2)), (Int('self.dtype') == IntVal(5)), (Int('self.dtype') == IntVal(15)), (Int('self.dtype') == IntVal(27))), IntVal(2), IntVal(1))))) <= If(Or((Int('source.dtype') == IntVal(4)), (Int('source.dtype') == IntVal(7)), (Int('source.dtype') == IntVal(29)), (Int('source.dtype') == IntVal(9))), IntVal(8), If((Int('source.dtype') == IntVal(10)), IntVal(16), If(Or((Int('source.dtype') == IntVal(3)), (Int('source.dtype') == IntVal(6)), (Int('source.dtype') == IntVal(28)), (Int('source.dtype') == IntVal(8))), IntVal(4), If(Or((Int('source.dtype') == IntVal(2)), (Int('source.dtype') == IntVal(5)), (Int('source.dtype') == IntVal(15)), (Int('source.dtype') == IntVal(27))), IntVal(2), IntVal(1))))))))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
