"""Combined + Z3-optimized constraints for _ZN2at6native10arange_outERKN3c106ScalarERNS_6TensorE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native10arange_outERKN3c106ScalarERNS_6TensorE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('end', 'Scalar'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Or((Int('out.dtype') == IntVal(0)), (Int('out.dtype') == IntVal(1)), (Int('out.dtype') == IntVal(2)), (Int('out.dtype') == IntVal(3)), (Int('out.dtype') == IntVal(4)), (Int('out.dtype') == IntVal(5)), (Int('out.dtype') == IntVal(6)), (Int('out.dtype') == IntVal(7)), (Int('out.dtype') == IntVal(15))), Or(Not(Or((Int('end.dtype') == IntVal(5)), (Int('end.dtype') == IntVal(6)), (Int('end.dtype') == IntVal(7)), (Int('end.dtype') == IntVal(15)), (Int('end.dtype') == IntVal(23)), (Int('end.dtype') == IntVal(24)), (Int('end.dtype') == IntVal(25)), (Int('end.dtype') == IntVal(26)), (Int('end.dtype') == IntVal(44)))), (Real('end.real_val') >= RealVal(0))), Or((Int('end.dtype') == IntVal(5)), (Int('end.dtype') == IntVal(6)), (Int('end.dtype') == IntVal(7)), (Int('end.dtype') == IntVal(15)), (Int('end.dtype') == IntVal(23)), (Int('end.dtype') == IntVal(24)), (Int('end.dtype') == IntVal(25)), (Int('end.dtype') == IntVal(26)), (Int('end.dtype') == IntVal(44)), (Int('end.int_val') >= IntVal(0))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
