"""Combined + Z3-optimized constraints for _ZN2at6native8ones_outEN3c108ArrayRefIlEERNS_6TensorE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native8ones_outEN3c108ArrayRefIlEERNS_6TensorE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('size', 'int[]'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('out.ndim') >= IntVal(0)), Or(And(Or((IntVal(0) >= Int('size.length')), (Select(Array('size.data', IntSort(), IntSort()), IntVal(0)) >= IntVal(0))), Or((IntVal(1) >= Int('size.length')), (Select(Array('size.data', IntSort(), IntSort()), IntVal(1)) >= IntVal(0))), Or((IntVal(2) >= Int('size.length')), (Select(Array('size.data', IntSort(), IntSort()), IntVal(2)) >= IntVal(0))), Or((IntVal(3) >= Int('size.length')), (Select(Array('size.data', IntSort(), IntSort()), IntVal(3)) >= IntVal(0))), Or((IntVal(4) >= Int('size.length')), (Select(Array('size.data', IntSort(), IntSort()), IntVal(4)) >= IntVal(0))), Or((IntVal(5) >= Int('size.length')), (Select(Array('size.data', IntSort(), IntSort()), IntVal(5)) >= IntVal(0)))), And(Not((Int('size.length') <= IntVal(0))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(0)) == IntVal(0))), And(Not((Int('size.length') <= IntVal(1))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(1)) == IntVal(0))), And(Not((Int('size.length') <= IntVal(2))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(2)) == IntVal(0))), And(Not((Int('size.length') <= IntVal(3))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(3)) == IntVal(0))), And(Not((Int('size.length') <= IntVal(4))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(4)) == IntVal(0))), And(Not((Int('size.length') <= IntVal(5))), (Select(Array('size.data', IntSort(), IntSort()), IntVal(5)) == IntVal(0)))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    size = IntArrayVar('size')
    out = TensorVar('out')
    return {'size': size, 'out': out}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
