"""Combined + Z3-optimized constraints for _ZN2at6native10_trilinearERKNS_6TensorES3_S3_N3c108ArrayRefIlEES6_S6_S6_l.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native10_trilinearERKNS_6TensorES3_S3_N3c108ArrayRefIlEES6_S6_S6_l (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('i1', 'Tensor'), ('i2', 'Tensor'), ('i3', 'Tensor'), ('expand1', 'int[]'), ('expand2', 'int[]'), ('expand3', 'int[]'), ('sumdim', 'int[]'), ('unroll_dim', 'int')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('i1.ndim') == IntVal(2)), (Int('i2.ndim') == IntVal(3)), (Int('i3.ndim') == IntVal(2)), (Int('i1.dtype') == Int('i2.dtype')), (Int('i1.dtype') == Int('i3.dtype')), Or((IntVal(5) == Int('i1.dtype')), (IntVal(6) == Int('i1.dtype')), (IntVal(7) == Int('i1.dtype')), (IntVal(15) == Int('i1.dtype'))), (Int('expand1.length') == IntVal(2)), (Select(Array('expand1.data', IntSort(), IntSort()), IntVal(0)) == IntVal(1)), (Select(Array('expand1.data', IntSort(), IntSort()), IntVal(1)) == IntVal(3)), (Int('expand2.length') == IntVal(1)), (Select(Array('expand2.data', IntSort(), IntSort()), IntVal(0)) == IntVal(0)), (Int('expand3.length') == IntVal(2)), (Select(Array('expand3.data', IntSort(), IntSort()), IntVal(0)) == IntVal(1)), (Select(Array('expand3.data', IntSort(), IntSort()), IntVal(1)) == IntVal(2)), (Int('sumdim.length') == IntVal(2)), (Select(Array('sumdim.data', IntSort(), IntSort()), IntVal(0)) == IntVal(2)), (Select(Array('sumdim.data', IntSort(), IntSort()), IntVal(1)) == IntVal(3)), (Select(Array('i1.sizes', IntSort(), IntSort()), IntVal(1)) == Select(Array('i2.sizes', IntSort(), IntSort()), IntVal(1))), (Select(Array('i3.sizes', IntSort(), IntSort()), IntVal(1)) == Select(Array('i2.sizes', IntSort(), IntSort()), IntVal(2))), (Select(Array('i1.sizes', IntSort(), IntSort()), IntVal(0)) == Select(Array('i3.sizes', IntSort(), IntSort()), IntVal(0))), (Int('unroll_dim') >= IntVal(0)), Not((IntVal(4) <= Int('unroll_dim'))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    i1 = TensorVar('i1')
    i2 = TensorVar('i2')
    i3 = TensorVar('i3')
    return {'i1': i1, 'i2': i2, 'i3': i3}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
