"""Combined + Z3-optimized constraints for _ZN2at6native9logit_outERKNS_6TensorESt8optionalIdERS1_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from mobile.generator.constraints.model import same_shape

ENTRY = '_ZN2at6native9logit_outERKNS_6TensorESt8optionalIdERS1_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('eps', 'float?'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    self_t = TensorVar('self')
    out_t = TensorVar('out')
    out_ok = Or(out_t.numel() == 0, same_shape(out_t, self_t))
    return [
        Not(And(Not((Int('self.dtype') == IntVal(8))), Not((Int('self.dtype') == IntVal(9))), Not((Int('self.dtype') == IntVal(10))), Or((Int('out.dtype') == IntVal(5)), (Int('out.dtype') == IntVal(6)), (Int('out.dtype') == IntVal(7)), (Int('out.dtype') == IntVal(8)), (Int('out.dtype') == IntVal(9)), (Int('out.dtype') == IntVal(10)), (Int('out.dtype') == IntVal(15))), out_ok)),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    out = TensorVar('out')
    return {'self': self, 'out': out}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
