"""Combined + Z3-optimized constraints for _ZN2at6native20_linalg_check_errorsERKNS_6TensorESt17basic_string_viewIcSt11char_traitsIcEEb.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native20_linalg_check_errorsERKNS_6TensorESt17basic_string_viewIcSt11char_traitsIcEEb (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('info', 'Tensor'), ('api_name', 'str'), ('is_matrix', 'bool')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('info.dtype') == IntVal(3)), (Real('info.data_lo') == RealVal(0)), (Real('info.data_hi') == RealVal(0)))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    info = TensorVar('info')
    return {'info': info}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
