"""Combined + Z3-optimized constraints for _ZN2at6native16searchsorted_cpuERKNS_6TensorERKN3c106ScalarEbbSt8optionalISt17basic_string_viewIcSt11char_traitsIcEEERKS8_IS1_E.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native16searchsorted_cpuERKNS_6TensorERKN3c106ScalarEbbSt8optionalISt17basic_string_viewIcSt11char_traitsIcEEERKS8_IS1_E (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('sorted_sequence', 'Tensor'), ('self', 'Scalar'), ('out_int32', 'bool'), ('right', 'bool'), ('side', 'str?'), ('sorter', 'Tensor?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((IntVal(1) == Int('sorted_sequence.ndim')), Or((IntVal(0) == Int('sorted_sequence.dtype')), (IntVal(1) == Int('sorted_sequence.dtype')), (IntVal(2) == Int('sorted_sequence.dtype')), (IntVal(3) == Int('sorted_sequence.dtype')), (IntVal(4) == Int('sorted_sequence.dtype')), (IntVal(5) == Int('sorted_sequence.dtype')), (IntVal(6) == Int('sorted_sequence.dtype')), (IntVal(7) == Int('sorted_sequence.dtype')), (IntVal(15) == Int('sorted_sequence.dtype'))), Not((Int('self.dtype') == IntVal(8))), Not((Int('self.dtype') == IntVal(9))), Not((Int('self.dtype') == IntVal(10))), Or(Not(Bool('side.present')), And(Or((IntVal(0) == Int('side.val')), (IntVal(1) == Int('side.val'))), Or(Not(Bool('right')), (IntVal(1) == Int('side.val'))))), Or(Not(Bool('sorter.present')), And((IntVal(1) == Int('sorter.val.ndim')), (Select(Array('sorter.val.sizes', IntSort(), IntSort()), IntVal(0)) == Select(Array('sorted_sequence.sizes', IntSort(), IntSort()), IntVal(0))), (IntVal(4) == Int('sorter.val.dtype')), (IntVal(16) <= Select(Array('sorter.val.sizes', IntSort(), IntSort()), IntVal(0))))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
