"""Combined + Z3-optimized constraints for _ZN2at6native32structured_special_bessel_j0_out4implERKNS_6TensorES4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from mobile.generator.constraints.model import same_shape, out_is_broadcast

ENTRY = '_ZN2at6native32structured_special_bessel_j0_out4implERKNS_6TensorES4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('x', 'Tensor'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    _out = TensorVar('out')
    _in = TensorVar('x')
    out_ok = Or(_out.numel() == 0, same_shape(_out, _in))
    return [
        Not(And(Or((Int('x.dtype') == IntVal(0)), (Int('x.dtype') == IntVal(1)), (Int('x.dtype') == IntVal(2)), (Int('x.dtype') == IntVal(3)), (Int('x.dtype') == IntVal(4)), (Int('x.dtype') == IntVal(27)), (Int('x.dtype') == IntVal(28)), (Int('x.dtype') == IntVal(29)), (Int('x.dtype') == IntVal(11)), (Int('x.dtype') == IntVal(6)), (Int('x.dtype') == IntVal(7))), Or((Int('out.dtype') == IntVal(5)), (Int('out.dtype') == IntVal(15)), (Int('out.dtype') == IntVal(6)), (Int('out.dtype') == IntVal(7)), (Int('out.dtype') == IntVal(8)), (Int('out.dtype') == IntVal(9)), (Int('out.dtype') == IntVal(10))), out_ok)),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
