"""Combined + Z3-optimized constraints for _ZN2at6native10addbmm_outERKNS_6TensorES3_S3_RKN3c106ScalarES7_RS1_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native10addbmm_outERKNS_6TensorES3_S3_RKN3c106ScalarES7_RS1_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('batch1', 'Tensor'), ('batch2', 'Tensor'), ('beta', 'Scalar'), ('alpha', 'Scalar'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((IntVal(3) == Int('batch1.ndim')), (IntVal(3) == Int('batch2.ndim')), (Select(Array('batch1.sizes', IntSort(), IntSort()), IntVal(0)) == Select(Array('batch2.sizes', IntSort(), IntSort()), IntVal(0))), (Select(Array('batch1.sizes', IntSort(), IntSort()), IntVal(2)) == Select(Array('batch2.sizes', IntSort(), IntSort()), IntVal(1))), (IntVal(2) >= Int('self.ndim')), Or((IntVal(1) == Select(Array('self.sizes', IntSort(), IntSort()), (IntVal(-1) + Int('self.ndim')))), (Select(Array('self.sizes', IntSort(), IntSort()), (IntVal(-1) + Int('self.ndim'))) == Select(Array('batch2.sizes', IntSort(), IntSort()), IntVal(2))), Not((IntVal(1) <= Int('self.ndim')))), Or((IntVal(1) == Select(Array('self.sizes', IntSort(), IntSort()), (IntVal(-2) + Int('self.ndim')))), (Select(Array('self.sizes', IntSort(), IntSort()), (IntVal(-2) + Int('self.ndim'))) == Select(Array('batch1.sizes', IntSort(), IntSort()), IntVal(1))), Not((IntVal(2) <= Int('self.ndim')))), (Int('self.dtype') == Int('batch2.dtype')), (Int('batch1.dtype') == Int('batch2.dtype')), (Int('out.dtype') == Int('batch2.dtype')), Or((IntVal(0) == Int('self.dtype')), (IntVal(1) == Int('self.dtype')), (IntVal(2) == Int('self.dtype')), (IntVal(3) == Int('self.dtype')), (IntVal(4) == Int('self.dtype')), (IntVal(5) == Int('self.dtype')), (IntVal(6) == Int('self.dtype')), (IntVal(7) == Int('self.dtype')), (IntVal(9) == Int('self.dtype')), (IntVal(10) == Int('self.dtype')), (IntVal(15) == Int('self.dtype')), (IntVal(23) == Int('self.dtype')), (IntVal(24) == Int('self.dtype')), (IntVal(25) == Int('self.dtype')), (IntVal(26) == Int('self.dtype'))),
        # addbmm_impl_ calls beta.to<complex<double>>() and writes the result
        # into a real-typed output: a COMPLEX beta/alpha then fails with
        # "result type Complex* can't be cast to ..." (real tensor) or
        # "Unknown Complex ScalarType for Float8_*" (float8 tensor). So when the
        # tensor dtype is not complex, beta and alpha must not be complex.
        Implies(Not(Or(Int('self.dtype') == IntVal(8), Int('self.dtype') == IntVal(9), Int('self.dtype') == IntVal(10))),
                And(Not(Or(Int('beta.dtype') == IntVal(8), Int('beta.dtype') == IntVal(9), Int('beta.dtype') == IntVal(10))),
                    Not(Or(Int('alpha.dtype') == IntVal(8), Int('alpha.dtype') == IntVal(9), Int('alpha.dtype') == IntVal(10))))),
        # Small-integer accumulation: addbmm sums batch1@batch2 over the batch
        # dim, so for low-range int dtypes (u8,i8,i16,i32) random data times the
        # beta/alpha scale overflows the type ("value cannot be converted ...
        # without overflow"). Bound the element values and the scalar scales for
        # those dtypes only; floats/i64 stay free.
        Implies(Or(Int('self.dtype') == IntVal(0), Int('self.dtype') == IntVal(1), Int('self.dtype') == IntVal(2), Int('self.dtype') == IntVal(3)),
                And(Real('self.data_lo') >= RealVal(-1), Real('self.data_hi') <= RealVal(1),
                    Real('batch1.data_lo') >= RealVal(-1), Real('batch1.data_hi') <= RealVal(1),
                    Real('batch2.data_lo') >= RealVal(-1), Real('batch2.data_hi') <= RealVal(1),
                    Real('beta.real_val') >= RealVal(-1), Real('beta.real_val') <= RealVal(1),
                    Int('beta.int_val') >= IntVal(-1), Int('beta.int_val') <= IntVal(1),
                    Real('alpha.real_val') >= RealVal(-1), Real('alpha.real_val') <= RealVal(1),
                    Int('alpha.int_val') >= IntVal(-1), Int('alpha.int_val') <= IntVal(1))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    batch1 = TensorVar('batch1')
    batch2 = TensorVar('batch2')
    beta = ScalarVar('beta')
    alpha = ScalarVar('alpha')
    out = TensorVar('out')
    return {'self': self, 'batch1': batch1, 'batch2': batch2, 'beta': beta, 'alpha': alpha, 'out': out}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
