"""Combined + Z3-optimized constraints for _ZN2at6native25structured_softshrink_out4implERKNS_6TensorERKN3c106ScalarES4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from model import same_shape

ENTRY = '_ZN2at6native25structured_softshrink_out4implERKNS_6TensorERKN3c106ScalarES4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('lambd', 'Scalar'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    _self = TensorVar('self')
    _out = TensorVar('out')
    out_ok = Or(_out.numel() == 0, same_shape(_out, _self))
    return [
        Not(And(Not(Bool('lambd.is_inf')), Not(Bool('lambd.is_nan')), Or((IntVal(5) == Int('self.dtype')), (IntVal(15) == Int('self.dtype')), (IntVal(6) == Int('self.dtype')), (IntVal(7) == Int('self.dtype'))), Not((Int('lambd.dtype') == IntVal(8))), Not((Int('lambd.dtype') == IntVal(9))), Not((Int('lambd.dtype') == IntVal(10))), (Int('out.dtype') == Int('self.dtype')), (RealVal(0) <= If(Or((Int('lambd.dtype') == IntVal(0)), (Int('lambd.dtype') == IntVal(1)), (Int('lambd.dtype') == IntVal(2)), (Int('lambd.dtype') == IntVal(3)), (Int('lambd.dtype') == IntVal(4)), (Int('lambd.dtype') == IntVal(27)), (Int('lambd.dtype') == IntVal(28)), (Int('lambd.dtype') == IntVal(29)), (Int('lambd.dtype') == IntVal(11))), ToReal(Int('lambd.int_val')), Real('lambd.real_val'))), out_ok)),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    lambd = ScalarVar('lambd')
    out = TensorVar('out')
    return {'self': self, 'lambd': lambd, 'out': out}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
