"""Combined + Z3-optimized constraints for _ZN2at6native6linearERKNS_6TensorES3_RKSt8optionalIS1_E.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native6linearERKNS_6TensorES3_RKSt8optionalIS1_E (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('input', 'Tensor'), ('weight', 'Tensor'), ('bias', 'Tensor?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((IntVal(1) <= Int('input.ndim')), (IntVal(1) <= Int('weight.ndim')), (IntVal(2) >= Int('weight.ndim')), (Select(Array('input.sizes', IntSort(), IntSort()), (IntVal(-1) + Int('input.ndim'))) == Select(Array('weight.sizes', IntSort(), IntSort()), (IntVal(-1) + Int('weight.ndim')))), (Int('input.dtype') == Int('weight.dtype')), Or((Int('input.dtype') == IntVal(0)), (Int('input.dtype') == IntVal(1)), (Int('input.dtype') == IntVal(2)), (Int('input.dtype') == IntVal(3)), (Int('input.dtype') == IntVal(4)), (Int('input.dtype') == IntVal(5)), (Int('input.dtype') == IntVal(6)), (Int('input.dtype') == IntVal(7)), (Int('input.dtype') == IntVal(9)), (Int('input.dtype') == IntVal(10)), (Int('input.dtype') == IntVal(15))), Or(Not(Bool('bias.present')), And((Int('bias.val.dtype') == Int('input.dtype')), (IntVal(2) == Int('weight.ndim')), Or((IntVal(0) == Int('bias.val.ndim')), And((IntVal(1) == Int('bias.val.ndim')), Or((Select(Array('bias.val.sizes', IntSort(), IntSort()), IntVal(0)) == Select(Array('weight.sizes', IntSort(), IntSort()), IntVal(0))), (IntVal(1) == Select(Array('bias.val.sizes', IntSort(), IntSort()), IntVal(0)))))))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    input = TensorVar('input')
    weight = TensorVar('weight')
    bias = OptVar('bias', TensorVar('bias' + '.val'))
    return {'input': input, 'weight': weight, 'bias': bias}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
