"""Combined + Z3-optimized constraints for _ZN2at6native19structured_ceil_out4implERKNS_6TensorES4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar, same_shape

ENTRY = '_ZN2at6native19structured_ceil_out4implERKNS_6TensorES4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Or(TensorVar('out').numel() == 0, same_shape(TensorVar('out'), TensorVar('self'))), (Int('self.ndim') >= IntVal(0)), Or((Int('self.dtype') == IntVal(0)), (Int('self.dtype') == IntVal(1)), (Int('self.dtype') == IntVal(2)), (Int('self.dtype') == IntVal(3)), (Int('self.dtype') == IntVal(4)), (Int('self.dtype') == IntVal(5)), (Int('self.dtype') == IntVal(6)), (Int('self.dtype') == IntVal(7)), (Int('self.dtype') == IntVal(15))), (Int('out.dtype') == Int('self.dtype')))),
    ]


def get_axioms() -> list:
    return []

def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
