"""Combined + Z3-optimized constraints for _ZN2at6native12unsafe_splitERKNS_6TensorEll.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native12unsafe_splitERKNS_6TensorEll (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('split_size', 'int'), ('dim', 'int')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('split_size') >= IntVal(0)), (Int('dim') >= (IntVal(-1) * Int('self.ndim'))), Not((Int('self.ndim') <= Int('dim'))), Or(Not((Int('split_size') <= IntVal(0))), (Select(Array('self.sizes', IntSort(), IntSort()), If((Int('dim') >= IntVal(0)), Int('dim'), (Int('self.ndim') + Int('dim')))) == IntVal(0))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    split_size = Int('split_size')
    dim = Int('dim')
    return {'self': self, 'split_size': split_size, 'dim': dim}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
