"""Combined + Z3-optimized constraints for _ZN2at6native19grid_sampler_2d_cpuERKNS_6TensorES3_llb.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native19grid_sampler_2d_cpuERKNS_6TensorES3_llb (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('input', 'Tensor'), ('grid', 'Tensor'), ('interpolation_mode', 'int'), ('padding_mode', 'int'), ('align_corners', 'bool')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    #
    # HAND-ADDED (not from the extractor) — keep across re-syncs. The two enum arguments
    # are bounded to their real ranges: interpolation_mode is GridSamplerInterpolation
    # {Bilinear=0, Nearest=1, Bicubic=2} and padding_mode is GridSamplerPadding
    # {Zeros=0, Border=1, Reflection=2}. THIS op's meta kernel rejects anything else
    # outright ("Invalid interpolation mode"), so an unbounded enum does not produce a
    # divergence to look at — it produces no graph at all, and the op drops out of the
    # corpus (measured 2/8 seeded without this, 8/8 with it). Note the 3d and backward
    # variants are deliberately NOT bounded: their kernels accept out-of-range values, so
    # there the disagreement between eager and the runtime is a real finding to expose.
    return [
        Not(And((Int('interpolation_mode') >= IntVal(0)), (Int('interpolation_mode') <= IntVal(2)), (Int('padding_mode') >= IntVal(0)), (Int('padding_mode') <= IntVal(2)), (IntVal(4) == Int('input.ndim')), (IntVal(4) == Int('grid.ndim')), (IntVal(2) == Select(Array('grid.sizes', IntSort(), IntSort()), IntVal(3))), (Select(Array('input.sizes', IntSort(), IntSort()), IntVal(0)) == Select(Array('grid.sizes', IntSort(), IntSort()), IntVal(0))), Or((IntVal(5) == Int('input.dtype')), (IntVal(6) == Int('input.dtype')), (IntVal(7) == Int('input.dtype')), (IntVal(15) == Int('input.dtype'))), (Int('grid.dtype') == Int('input.dtype')))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    input = TensorVar('input')
    grid = TensorVar('grid')
    return {'input': input, 'grid': grid}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
