"""Combined + Z3-optimized constraints for _ZN2at6native23batch_norm_backward_cpuERKNS_6TensorES3_RKSt8optionalIS1_ES7_S7_S7_S7_bdSt5arrayIbLm3EE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native23batch_norm_backward_cpuERKNS_6TensorES3_RKSt8optionalIS1_ES7_S7_S7_S7_bdSt5arrayIbLm3EE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('grad_out', 'Tensor'), ('input', 'Tensor'), ('weight', 'Tensor?'), ('running_mean', 'Tensor?'), ('running_var', 'Tensor?'), ('save_mean', 'Tensor?'), ('save_invstd', 'Tensor?'), ('train', 'bool'), ('eps', 'float'), ('output_mask', 'bool[3]')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Or((IntVal(5) == Int('input.dtype')), (IntVal(6) == Int('input.dtype')), (IntVal(7) == Int('input.dtype')), (IntVal(15) == Int('input.dtype'))), (IntVal(2) <= Int('input.ndim')), (Int('grad_out.dtype') == Int('input.dtype')), Or(Not(Bool('weight.present')), (IntVal(1) == Int('weight.val.ndim'))), Or(Not(Bool('running_mean.present')), (IntVal(1) == Int('running_mean.val.ndim'))), Or(Not(Bool('running_var.present')), (IntVal(1) == Int('running_var.val.ndim'))), Or(Not(Bool('save_mean.present')), (IntVal(1) == Int('save_mean.val.ndim'))), Or(Not(Bool('save_invstd.present')), (IntVal(1) == Int('save_invstd.val.ndim'))), Or(And(Or(Not(Bool('weight.present')), (Int('weight.val.dtype') == Int('input.dtype'))), Or(Not(Bool('running_mean.present')), (Int('running_mean.val.dtype') == Int('input.dtype'))), Or(Not(Bool('running_var.present')), (Int('running_var.val.dtype') == Int('input.dtype'))), Or(Not(Bool('save_mean.present')), (Int('save_mean.val.dtype') == Int('input.dtype'))), Or(Not(Bool('save_invstd.present')), (Int('save_invstd.val.dtype') == Int('input.dtype')))), And(Or((IntVal(5) == Int('input.dtype')), (IntVal(15) == Int('input.dtype'))), Or(Not(Bool('weight.present')), (IntVal(6) == Int('weight.val.dtype'))), Or(Not(Bool('running_mean.present')), (IntVal(6) == Int('running_mean.val.dtype'))), Or(Not(Bool('running_var.present')), (IntVal(6) == Int('running_var.val.dtype'))), Or(Not(Bool('save_mean.present')), (IntVal(6) == Int('save_mean.val.dtype'))), Or(Not(Bool('save_invstd.present')), (IntVal(6) == Int('save_invstd.val.dtype'))))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    grad_out = TensorVar('grad_out')
    input = TensorVar('input')
    weight = OptVar('weight', TensorVar('weight' + '.val'))
    running_mean = OptVar('running_mean', TensorVar('running_mean' + '.val'))
    running_var = OptVar('running_var', TensorVar('running_var' + '.val'))
    save_mean = OptVar('save_mean', TensorVar('save_mean' + '.val'))
    save_invstd = OptVar('save_invstd', TensorVar('save_invstd' + '.val'))
    return {'grad_out': grad_out, 'input': input, 'weight': weight, 'running_mean': running_mean, 'running_var': running_var, 'save_mean': save_mean, 'save_invstd': save_invstd}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
