"""Combined + Z3-optimized constraints for _ZN2at6native10_make_dualERKNS_6TensorES3_l.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native10_make_dualERKNS_6TensorES3_l (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('primal', 'Tensor'), ('tangent', 'Tensor'), ('level', 'int')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And((Int('tangent.ndim') == Int('primal.ndim')), Or((Int('tangent.ndim') <= IntVal(0)), (Select(Array('tangent.sizes', IntSort(), IntSort()), IntVal(0)) == Select(Array('primal.sizes', IntSort(), IntSort()), IntVal(0)))), Or((Int('tangent.ndim') <= IntVal(1)), (Select(Array('tangent.sizes', IntSort(), IntSort()), IntVal(1)) == Select(Array('primal.sizes', IntSort(), IntSort()), IntVal(1)))), Or((Int('tangent.ndim') <= IntVal(2)), (Select(Array('tangent.sizes', IntSort(), IntSort()), IntVal(2)) == Select(Array('primal.sizes', IntSort(), IntSort()), IntVal(2)))), Or((Int('tangent.ndim') <= IntVal(3)), (Select(Array('tangent.sizes', IntSort(), IntSort()), IntVal(3)) == Select(Array('primal.sizes', IntSort(), IntSort()), IntVal(3)))), Or((Int('tangent.ndim') <= IntVal(4)), (Select(Array('tangent.sizes', IntSort(), IntSort()), IntVal(4)) == Select(Array('primal.sizes', IntSort(), IntSort()), IntVal(4)))), Or((Int('tangent.dtype') == IntVal(5)), (Int('tangent.dtype') == IntVal(6)), (Int('tangent.dtype') == IntVal(7)), (Int('tangent.dtype') == IntVal(15)), (Int('tangent.dtype') == IntVal(23)), (Int('tangent.dtype') == IntVal(24)), (Int('tangent.dtype') == IntVal(25)), (Int('tangent.dtype') == IntVal(26)), (Int('tangent.dtype') == IntVal(44)), (Int('tangent.dtype') == IntVal(8)), (Int('tangent.dtype') == IntVal(9)), (Int('tangent.dtype') == IntVal(10))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
