"""Combined + Z3-optimized constraints for _ZN2at6native5randnEN3c108ArrayRefIlEESt8optionalINS_9GeneratorEES4_INS1_10ScalarTypeEES4_INS1_6LayoutEES4_INS1_6DeviceEES4_IbE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native5randnEN3c108ArrayRefIlEESt8optionalINS_9GeneratorEES4_INS1_10ScalarTypeEES4_INS1_6LayoutEES4_INS1_6DeviceEES4_IbE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('size', 'int[]'), ('generator', 'Generator?'), ('dtype', 'int?'), ('layout', 'int?'), ('device', 'int?'), ('pin_memory', 'bool?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Or((IntVal(0) >= Int('size.length')), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(0)))), Or((IntVal(1) >= Int('size.length')), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(1)))), Or((IntVal(2) >= Int('size.length')), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(2)))), Or((IntVal(3) >= Int('size.length')), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(3)))), Or((IntVal(4) >= Int('size.length')), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(4)))), Or((IntVal(5) >= Int('size.length')), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(5)))), Or(And((Int('dtype.val') == IntVal(5)), Bool('dtype.present')), (Int('dtype.val') == IntVal(6)), Not(Bool('dtype.present')), And((Int('dtype.val') == IntVal(7)), Bool('dtype.present')), And((Int('dtype.val') == IntVal(15)), Bool('dtype.present')), And((Int('dtype.val') == IntVal(8)), Bool('dtype.present')), And((Int('dtype.val') == IntVal(9)), Bool('dtype.present')), And((Int('dtype.val') == IntVal(10)), Bool('dtype.present'))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    size = IntArrayVar('size')
    dtype = OptVar('dtype', Int('dtype' + '.val'))
    return {'size': size, 'dtype': dtype}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
