"""Combined + Z3-optimized constraints for _ZN2at6native21structured_argmax_out4implERKNS_6TensorESt8optionalIlEbS4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from mobile.generator.constraints.model import same_shape, out_is_broadcast

ENTRY = '_ZN2at6native21structured_argmax_out4implERKNS_6TensorESt8optionalIlEbS4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('dim', 'int?'), ('keepdim', 'bool'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    _out = TensorVar('out')
    out_ok = (_out.numel() == IntVal(0))
    return [
        Or(Not(out_ok), Not(And(Not((Int('self.dtype') == IntVal(8))), Not((Int('self.dtype') == IntVal(9))), Not((Int('self.dtype') == IntVal(10))), Not((Int('self.dtype') == IntVal(11))), If(Bool('dim.present'), And((Int('dim.val') >= (IntVal(-1) * Int('self.ndim'))), Not((Int('self.ndim') <= Int('dim.val'))), (Select(Array('self.sizes', IntSort(), IntSort()), If((Int('dim.val') >= IntVal(0)), Int('dim.val'), (Int('self.ndim') + Int('dim.val')))) >= IntVal(1))), And(Or((Int('self.ndim') <= IntVal(0)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(0)) >= IntVal(1))), Or((Int('self.ndim') <= IntVal(1)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(1)) >= IntVal(1))), Or((Int('self.ndim') <= IntVal(2)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(2)) >= IntVal(1))), Or((Int('self.ndim') <= IntVal(3)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(3)) >= IntVal(1))), Or((Int('self.ndim') <= IntVal(4)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(4)) >= IntVal(1))), Or((Int('self.ndim') <= IntVal(5)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(5)) >= IntVal(1))), Or((Int('self.ndim') <= IntVal(6)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(6)) >= IntVal(1))), Or((Int('self.ndim') <= IntVal(7)), (Select(Array('self.sizes', IntSort(), IntSort()), IntVal(7)) >= IntVal(1))))), (Int('out.dtype') == IntVal(4))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
