"""Combined + Z3-optimized constraints for _ZN2at6native9frexp_outERKNS_6TensorERS1_S4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from mobile.generator.constraints.model import same_shape, out_is_broadcast

ENTRY = '_ZN2at6native9frexp_outERKNS_6TensorERS1_S4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('mantissa', 'Tensor'), ('exponent', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    self = TensorVar('self')
    mantissa = TensorVar('mantissa')
    exponent = TensorVar('exponent')
    # frexp: mantissa and exponent both have the same shape as self.
    mant_ok = Or(mantissa.numel() == 0, same_shape(mantissa, self))
    exp_ok = Or(exponent.numel() == 0, same_shape(exponent, self))
    _orig = And((IntVal(3) == Int('_iter_c1c2c3_ntensors')), (IntVal(1) == Int('_iter_c1c2c3_ninputs')), (IntVal(2) == Int('_iter_c1c2c3_noutputs')), (Int('_iter_c1c2c3_common_dtype') == Int('self.dtype')), (Int('_iter_c1c2c3_dtype_0') == Int('mantissa.dtype')), (Bool('_iter_c1c2c3_is_scalar_0') == (IntVal(0) == Int('mantissa.ndim'))), (Int('_iter_c1c2c3_dtype_1') == IntVal(3)), (Bool('_iter_c1c2c3_is_scalar_1') == (IntVal(0) == Int('exponent.ndim'))), (Int('_iter_c1c2c3_dtype_2') == Int('self.dtype')), (Bool('_iter_c1c2c3_is_scalar_2') == (IntVal(0) == Int('self.ndim'))), Or((IntVal(5) == Int('self.dtype')), (IntVal(6) == Int('self.dtype')), (IntVal(7) == Int('self.dtype')), (IntVal(15) == Int('self.dtype'))), (Int('mantissa.dtype') == Int('self.dtype')), (IntVal(3) == Int('exponent.dtype')), Not(And(Not((IntVal(7) == Int('_iter_c1c2c3_dtype_0'))), Not((IntVal(6) == Int('_iter_c1c2c3_dtype_0'))), Not((IntVal(15) == Int('_iter_c1c2c3_dtype_0'))), Not((IntVal(5) == Int('_iter_c1c2c3_dtype_0'))))))
    return [
        Not(And(_orig, mant_ok, exp_ok)),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    mantissa = TensorVar('mantissa')
    exponent = TensorVar('exponent')
    return {'self': self, 'mantissa': mantissa, 'exponent': exponent}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
