"""Combined + Z3-optimized constraints for _ZN2at6native23bitwise_right_shift_outERKNS_6TensorERKN3c106ScalarERS1_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from model import same_shape, out_is_broadcast


ENTRY = '_ZN2at6native23bitwise_right_shift_outERKNS_6TensorERKN3c106ScalarERS1_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('other', 'Scalar'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    _out = TensorVar('out'); _self = TensorVar('self')
    out_ok_1 = Or(_out.numel() == 0, same_shape(_out, _self))
    return [
        Not(And(out_ok_1, (Int('tensor_s0_10.dtype') == Int('other.dtype')), Not(And(Not((IntVal(8) == Int('tensor_s0_10.dtype'))), Not((IntVal(5) == Int('tensor_s0_10.dtype'))), Not((IntVal(11) == Int('tensor_s0_10.dtype'))), Not((IntVal(15) == Int('tensor_s0_10.dtype'))), Not((IntVal(0) == Int('tensor_s0_10.dtype'))), Not((IntVal(1) == Int('tensor_s0_10.dtype'))), Not((IntVal(3) == Int('tensor_s0_10.dtype'))), Not((IntVal(4) == Int('tensor_s0_10.dtype'))), Not((IntVal(2) == Int('tensor_s0_10.dtype'))), Not((IntVal(7) == Int('tensor_s0_10.dtype'))), Not((IntVal(6) == Int('tensor_s0_10.dtype'))), Not((IntVal(10) == Int('tensor_s0_10.dtype'))), Not((IntVal(9) == Int('tensor_s0_10.dtype'))), Not((IntVal(23) == Int('tensor_s0_10.dtype'))), Not((IntVal(25) == Int('tensor_s0_10.dtype'))), Not((IntVal(24) == Int('tensor_s0_10.dtype'))), Not((IntVal(26) == Int('tensor_s0_10.dtype'))), Not((IntVal(44) == Int('tensor_s0_10.dtype'))), Not((IntVal(27) == Int('tensor_s0_10.dtype'))), Not((IntVal(28) == Int('tensor_s0_10.dtype'))), Not((IntVal(29) == Int('tensor_s0_10.dtype'))))), Or((IntVal(0) == Int('self.dtype')), (IntVal(1) == Int('self.dtype')), (IntVal(2) == Int('self.dtype')), (IntVal(3) == Int('self.dtype')), (IntVal(4) == Int('self.dtype')), (IntVal(11) == Int('self.dtype'))), Or((Int('other.dtype') == IntVal(0)), (Int('other.dtype') == IntVal(1)), (Int('other.dtype') == IntVal(2)), (Int('other.dtype') == IntVal(3)), (Int('other.dtype') == IntVal(4)), (Int('other.dtype') == IntVal(27)), (Int('other.dtype') == IntVal(28)), (Int('other.dtype') == IntVal(29)), (Int('other.dtype') == IntVal(11))), Or(Not((IntVal(11) == Int('other.dtype'))), Not((IntVal(11) == Int('self.dtype')))), Not((IntVal(11) == Int('out.dtype'))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    other = ScalarVar('other')
    out = TensorVar('out')
    tensor_s0_10 = TensorVar('tensor_s0_10')
    return {'self': self, 'other': other, 'out': out, 'tensor_s0_10': tensor_s0_10}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
