"""Combined + Z3-optimized constraints for _ZN2at6native9new_zerosERKNS_6TensorEN3c108ArrayRefIlEESt8optionalINS4_10ScalarTypeEES7_INS4_6LayoutEES7_INS4_6DeviceEES7_IbE.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = '_ZN2at6native9new_zerosERKNS_6TensorEN3c108ArrayRefIlEESt8optionalINS4_10ScalarTypeEES7_INS4_6LayoutEES7_INS4_6DeviceEES7_IbE (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('size', 'int[]'), ('dtype', 'int?'), ('layout', 'int?'), ('device', 'int?'), ('pin_memory', 'bool?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Or((Int('size.length') <= IntVal(0)), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(0)))), Or((Int('size.length') <= IntVal(1)), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(1)))), Or((Int('size.length') <= IntVal(2)), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(2)))), Or((Int('size.length') <= IntVal(3)), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(3)))), Or((Int('size.length') <= IntVal(4)), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(4)))), Or((Int('size.length') <= IntVal(5)), (IntVal(0) <= Select(Array('size.data', IntSort(), IntSort()), IntVal(5)))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
