"""Combined + Z3-optimized constraints for normal.float_float.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar

ENTRY = 'normal.float_float (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('mean', 'float'), ('std', 'float'), ('size', 'int[]'), ('generator', 'Generator?'), ('dtype', 'int?'), ('layout', 'int?'), ('device', 'int?'), ('pin_memory', 'bool?')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    return [
        Not(And(Or((Int('size.length') <= IntVal(0)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(0)) >= IntVal(0))), Or((Int('size.length') <= IntVal(1)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(1)) >= IntVal(0))), Or((Int('size.length') <= IntVal(2)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(2)) >= IntVal(0))), Or((Int('size.length') <= IntVal(3)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(3)) >= IntVal(0))), Or((Int('size.length') <= IntVal(4)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(4)) >= IntVal(0))), Or((Int('size.length') <= IntVal(5)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(5)) >= IntVal(0))), Or((Int('size.length') <= IntVal(6)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(6)) >= IntVal(0))), Or((Int('size.length') <= IntVal(7)), (Select(Array('size.data', IntSort(), IntSort()), IntVal(7)) >= IntVal(0))), (Real('std') >= RealVal(0)), Or(Not(Bool('dtype.present')), (Int('dtype.val') == IntVal(5)), (Int('dtype.val') == IntVal(6)), (Int('dtype.val') == IntVal(7)), (Int('dtype.val') == IntVal(8)), (Int('dtype.val') == IntVal(9)), (Int('dtype.val') == IntVal(10)), (Int('dtype.val') == IntVal(15))))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    pass
    return {}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
