"""Combined + Z3-optimized constraints for _ZN2at6native33structured_linalg_cholesky_ex_out4implERKNS_6TensorEbbS4_S4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar, same_shape, out_is_broadcast

ENTRY = '_ZN2at6native33structured_linalg_cholesky_ex_out4implERKNS_6TensorEbbS4_S4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('upper', 'bool'), ('check_errors', 'bool'), ('L', 'Tensor'), ('info', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    _self = TensorVar('self')
    _L = TensorVar('L')
    _info = TensorVar('info')
    L_ok = Or(_L.numel() == 0, same_shape(_L, _self))
    _iconds = [_info.ndim == _self.ndim - IntVal(2)]
    for _i in range(8):
        _iconds.append(Implies(IntVal(_i) < _info.ndim, _info.size(_i) == _self.size(_i)))
    info_ok = Or(_info.numel() == 0, And(*_iconds))
    return [
        Not(And(L_ok, info_ok, Or((IntVal(6) == Int('self.dtype')), (IntVal(7) == Int('self.dtype')), (IntVal(9) == Int('self.dtype')), (IntVal(10) == Int('self.dtype'))), (Int('self.ndim') >= IntVal(2)), (Select(Array('self.sizes', IntSort(), IntSort()), (IntVal(-1) + Int('self.ndim'))) == Select(Array('self.sizes', IntSort(), IntSort()), (IntVal(-2) + Int('self.ndim')))), (Int('L.dtype') == Int('self.dtype')), (IntVal(3) == Int('info.dtype')), Not(Bool('check_errors')))),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    L = TensorVar('L')
    info = TensorVar('info')
    return {'self': self, 'L': L, 'info': info}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
