"""Combined + Z3-optimized constraints for _ZN2at6native51structured__upsample_bilinear2d_aa_backward_out_cpu4implERKNS_6TensorEN3c108ArrayRefIlEES7_bSt8optionalIdES9_S4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

from z3 import *
from mobile.generator.constraints.model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar, same_shape, out_is_broadcast

ENTRY = '_ZN2at6native51structured__upsample_bilinear2d_aa_backward_out_cpu4implERKNS_6TensorEN3c108ArrayRefIlEES7_bSt8optionalIdES9_S4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('grad_output', 'Tensor'), ('output_size', 'int[]'), ('input_size', 'int[]'), ('align_corners', 'bool'), ('scales_h', 'float?'), ('scales_w', 'float?'), ('grad_input', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    grad_input = TensorVar('grad_input')
    isz = Array('input_size.data', IntSort(), IntSort())
    out_ok = Or(
        grad_input.numel() == IntVal(0),
        And(grad_input.ndim == IntVal(4),
            grad_input.size(0) == Select(isz, IntVal(0)),
            grad_input.size(1) == Select(isz, IntVal(1)),
            grad_input.size(2) == Select(isz, IntVal(2)),
            grad_input.size(3) == Select(isz, IntVal(3))),
    )
    return [
        Not(And(out_ok, Or((IntVal(6) == Int('grad_output.dtype')), (IntVal(7) == Int('grad_output.dtype'))), (Int('input_size.length') == IntVal(4)), (Int('output_size.length') == IntVal(2)), (IntVal(1) <= Select(Array('input_size.data', IntSort(), IntSort()), IntVal(2))), (IntVal(1) <= Select(Array('input_size.data', IntSort(), IntSort()), IntVal(3))), (IntVal(1) <= Select(Array('output_size.data', IntSort(), IntSort()), IntVal(0))), (IntVal(1) <= Select(Array('output_size.data', IntSort(), IntSort()), IntVal(1))), (Int('grad_output.ndim') == IntVal(4)), (Select(Array('grad_output.sizes', IntSort(), IntSort()), IntVal(0)) == Select(Array('input_size.data', IntSort(), IntSort()), IntVal(0))), (Select(Array('grad_output.sizes', IntSort(), IntSort()), IntVal(1)) == Select(Array('input_size.data', IntSort(), IntSort()), IntVal(1))), (Select(Array('grad_output.sizes', IntSort(), IntSort()), IntVal(2)) == Select(Array('output_size.data', IntSort(), IntSort()), IntVal(0))), (Select(Array('grad_output.sizes', IntSort(), IntSort()), IntVal(3)) == Select(Array('output_size.data', IntSort(), IntSort()), IntVal(1))), (Int('grad_input.dtype') == Int('grad_output.dtype')), out_ok)),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    grad_output = TensorVar('grad_output')
    output_size = IntArrayVar('output_size')
    input_size = IntArrayVar('input_size')
    grad_input = TensorVar('grad_input')
    return {'grad_output': grad_output, 'output_size': output_size, 'input_size': input_size, 'grad_input': grad_input}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
