"""Combined + Z3-optimized constraints for _ZN2at6native36structured_replication_pad2d_out_cpu4implERKNS_6TensorEN3c108ArrayRefIlEES4_.

Auto-generated by combine_constraints.py: the per-slice failure paths and axioms
of the source folder, merged into one simplified formula. Consumed by the same
concretizer/test harness as a normal slice (get_axioms carries the whole op
region; the harness still adds its own domain/size axioms)."""

import sys
sys.path.insert(0, '/data/jwen929/pytorch/z3')
from z3 import *
from model import TensorVar, ScalarVar, IntArrayVar, OptVar, TensorListVar
from model import same_shape

ENTRY = '_ZN2at6native36structured_replication_pad2d_out_cpu4implERKNS_6TensorEN3c108ArrayRefIlEES4_ (combined)'
IN_LOOP = False
LOOP_SAFE = True
_UNRESOLVED = frozenset([])


def get_unresolved_vars() -> frozenset:
    return _UNRESOLVED


_PARAMS = [('self', 'Tensor'), ('padding', 'int[]'), ('out', 'Tensor')]


def get_params() -> list:
    return _PARAMS


def get_constraints() -> list:
    # The harness adds Not(And(get_constraints())); wrapping the combined region
    # in Not() here means it adds back exactly the region. Returning it as a
    # (non-empty) constraint also keeps the slice "usable" rather than a stub.
    _self = TensorVar('self')
    _out = TensorVar('out')
    _pad = IntArrayVar('padding')
    _shape = And(
        _out.ndim == _self.ndim,
        _out.size(-1) == _self.size(-1) + _pad[0] + _pad[1],
        _out.size(-2) == _self.size(-2) + _pad[2] + _pad[3],
        Implies(_self.ndim >= 3, _out.size(-3) == _self.size(-3)),
        Implies(_self.ndim >= 4, _out.size(-4) == _self.size(-4)),
    )
    out_ok = Or(_out.numel() == 0, _shape)
    return [
        Not(And((IntVal(4) == Int('padding.length')), Or((IntVal(3) == Int('self.ndim')), (IntVal(4) == Int('self.ndim'))), If((IntVal(4) == Int('self.ndim')), And(Not((IntVal(0) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(1)))), Not((IntVal(0) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(2)))), Not((IntVal(0) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(3))))), And(Not((IntVal(0) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(0)))), Not((IntVal(0) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(1)))), Not((IntVal(0) == Select(Array('self.sizes', IntSort(), IntSort()), IntVal(2)))))), (IntVal(1) <= (If((IntVal(4) == Int('self.ndim')), Select(Array('self.sizes', IntSort(), IntSort()), IntVal(3)), Select(Array('self.sizes', IntSort(), IntSort()), IntVal(2))) + Select(Array('padding.data', IntSort(), IntSort()), IntVal(0)) + Select(Array('padding.data', IntSort(), IntSort()), IntVal(1)))), (IntVal(1) <= (If((IntVal(4) == Int('self.ndim')), Select(Array('self.sizes', IntSort(), IntSort()), IntVal(2)), Select(Array('self.sizes', IntSort(), IntSort()), IntVal(1))) + Select(Array('padding.data', IntSort(), IntSort()), IntVal(2)) + Select(Array('padding.data', IntSort(), IntSort()), IntVal(3)))), Or((IntVal(0) == Int('self.dtype')), (IntVal(1) == Int('self.dtype')), (IntVal(2) == Int('self.dtype')), (IntVal(3) == Int('self.dtype')), (IntVal(4) == Int('self.dtype')), (IntVal(5) == Int('self.dtype')), (IntVal(6) == Int('self.dtype')), (IntVal(7) == Int('self.dtype')), (IntVal(9) == Int('self.dtype')), (IntVal(10) == Int('self.dtype')), (IntVal(15) == Int('self.dtype'))), (Int('out.dtype') == Int('self.dtype')), out_ok)),
    ]


def get_axioms() -> list:
    return []


def get_vars() -> dict:
    self = TensorVar('self')
    out = TensorVar('out')
    return {'self': self, 'out': out}


def build_solver() -> Solver:
    s = Solver()
    s.add(*get_axioms())
    return s
